'use strict';
const fs = require('fs');

// Load the current words.json (after batch 1 ran but FAILED - so still original 1500)
// We re-run against original since gen_words.js exited with error before writing
const existing = JSON.parse(fs.readFileSync('./words.json', 'utf8'));
const existSet = new Set(existing.map(w => w.en.toLowerCase()));
console.log('Existing count:', existing.length);

// ── SECOND LARGE BATCH OF CANDIDATES ────────────────────────────────────────
const RAW2 = [

// ═══════════════ MORE B1 VERBS ═══════════════
["raise","підвищувати","verb","B1","general"],
["lower","знижувати","verb","B1","general"],
["consider","розглядати","verb","B1","general"],
["prepare","готуватися","verb","B1","general"],
["contact","зв'язуватися","verb","B1","communication"],
["communicate","спілкуватися","verb","B1","communication"],
["express","висловлювати","verb","B1","communication"],
["present","представляти","verb","B1","work"],
["lead","очолювати","verb","B1","work"],
["design","проектувати","verb","B1","general"],
["analyse","аналізувати","verb","B1","general"],
["measure","вимірювати","verb","B1","general"],
["test","тестувати","verb","B1","general"],
["collaborate","співпрацювати","verb","B1","work"],
["approve","схвалювати","verb","B1","work"],
["pollute","забруднювати","verb","B1","nature"],
["bother","турбувати","verb","B1","emotions"],
["forgive","прощати","verb","B1","emotions"],
["inspire","надихати","verb","B1","emotions"],
["publish","публікувати","verb","B1","general"],
["edit","редагувати","verb","B1","general"],
["access","отримувати доступ","verb","B1","technology"],
["stream","транслювати онлайн","verb","B1","technology"],
["lend","позичати (давати)","verb","B1","money"],
["earn","заробляти","verb","B1","money"],
["afford","мати змогу дозволити","verb","B1","money"],
["charge","стягувати плату","verb","B1","money"],
["invest","інвестувати","verb","B1","money"],
["save","економити","verb","B1","money"],
["book","бронювати","verb","B1","travel"],
["recycle","переробляти","verb","B1","nature"],
["protect","захищати","verb","B1","general"],
["damage","пошкоджувати","verb","B1","general"],
["survive","виживати","verb","B1","general"],
["escape","тікати","verb","B1","general"],
["avoid","уникати","verb","B1","general"],
["complain","скаржитися","verb","B1","emotions"],
["trust","довіряти","verb","B1","emotions"],
["doubt","сумніватися","verb","B1","emotions"],
["blame","звинувачувати","verb","B1","emotions"],
["encourage","заохочувати","verb","B1","emotions"],
["convince","переконувати","verb","B1","communication"],
["warn","попереджати","verb","B1","communication"],
["mention","зазначати","verb","B1","communication"],
["notice","помічати","verb","B1","general"],
["upload","завантажувати","verb","B1","technology"],
["download","скачувати","verb","B1","technology"],
["install","встановлювати","verb","B1","technology"],
["connect","підключати","verb","B1","technology"],
["update","оновлювати","verb","B1","technology"],
["delete","видаляти","verb","B1","technology"],
["share","ділитися","verb","B1","technology"],
["review","переглядати","verb","B1","general"],
["evaluate","оцінювати","verb","B1","general"],
["submit","подавати","verb","B1","school"],
["register","реєструватися","verb","B1","general"],
["cancel","скасовувати","verb","B1","general"],
["confirm","підтверджувати","verb","B1","general"],
["reject","відхиляти","verb","B1","general"],
["accept","приймати","verb","B1","general"],
["negotiate","домовлятися","verb","B1","work"],
["plan","планувати","verb","B1","general"],
["organize","організовувати","verb","B1","work"],
["manage","керувати","verb","B1","work"],
["achieve","досягати","verb","B1","general"],
["improve","покращувати","verb","B1","general"],
["develop","розвивати","verb","B1","general"],
["increase","збільшувати","verb","B1","general"],
["decrease","зменшувати","verb","B1","general"],
["reduce","скорочувати","verb","B1","general"],
["support","підтримувати","verb","B1","general"],
["prevent","запобігати","verb","B1","health"],
["recover","одужувати","verb","B1","health"],
["treat","лікувати","verb","B1","health"],
["recommend","рекомендувати","verb","B1","general"],
["require","вимагати","verb","B1","general"],
["provide","надавати","verb","B1","general"],
["translate","перекладати","verb","B1","school"],
["hire","наймати","verb","B1","work"],
["apply","подавати заяву","verb","B1","work"],
["attend","відвідувати","verb","B1","general"],
["create","створювати","verb","B1","general"],
["search","шукати","verb","B1","general"],
["discover","відкривати","verb","B1","general"],
["explore","досліджувати","verb","B1","general"],
["investigate","розслідувати","verb","B1","general"],
["solve","вирішувати","verb","B1","general"],
["schedule","планувати (розклад)","verb","B1","work"],
["compare","порівнювати","verb","B1","general"],
["depend","залежати","verb","B1","general"],
["expect","очікувати","verb","B1","general"],
["examine","обстежувати","verb","B1","health"],
["tour","їздити на екскурсію","verb","B1","travel"],
["assist","допомагати","verb","B1","general"],
["adapt","адаптуватися","verb","B1","general"],
["adjust","коригувати","verb","B1","general"],
["respond","відповідати","verb","B1","communication"],
["react","реагувати","verb","B1","general"],
["handle","поводитися з","verb","B1","general"],
["obtain","отримувати","verb","B1","general"],
["retain","зберігати","verb","B1","general"],
["maintain","підтримувати (рівень)","verb","B1","general"],
["establish","встановлювати","verb","B1","general"],
["found","засновувати","verb","B1","general"],
["expand","розширювати","verb","B1","general"],
["promote","просувати","verb","B1","work"],
["transfer","передавати","verb","B1","general"],
["exchange","обмінювати","verb","B1","general"],
["combine","поєднувати","verb","B1","general"],
["separate","роз'єднувати","verb","B1","general"],
["replace","замінювати","verb","B1","general"],
["remove","усувати","verb","B1","general"],
["include","включати","verb","B1","general"],
["exclude","виключати","verb","B1","general"],
["rely","покладатися","verb","B1","general"],
["relate","відноситися","verb","B1","general"],
["affect","впливати на","verb","B1","general"],
["involve","залучати","verb","B1","general"],
["ensure","забезпечувати","verb","B1","general"],
["indicate","вказувати","verb","B1","general"],
["suggest","пропонувати","verb","B1","general"],
["argue","стверджувати","verb","B1","communication"],
["claim","стверджувати","verb","B1","communication"],
["prove","доводити","verb","B1","general"],
["demonstrate","демонструвати","verb","B1","general"],
["represent","представляти","verb","B1","general"],
["reflect","відображати","verb","B1","general"],
["display","показувати","verb","B1","general"],
["illustrate","ілюструвати","verb","B1","general"],
["calculate","обчислювати","verb","B1","school"],
["estimate","оцінювати (кількість)","verb","B1","general"],
["predict","передбачати","verb","B1","general"],
["observe","спостерігати","verb","B1","general"],
["record","записувати","verb","B1","general"],
["collect","збирати (дані)","verb","B1","general"],
["categorize","класифікувати","verb","B1","general"],
["summarize","підсумовувати","verb","B1","school"],
["quote","цитувати","verb","B1","school"],
["refer","посилатися","verb","B1","school"],
["practise","практикувати","verb","B1","school"],
["revise","повторювати (матеріал)","verb","B1","school"],
["concentrate","зосереджуватися","verb","B1","school"],
["focus","фокусуватися","verb","B1","general"],
["decide","вирішувати","verb","B1","general"],
["intend","мати намір","verb","B1","general"],
["aim","прагнути","verb","B1","general"],
["attempt","намагатися","verb","B1","general"],
["succeed","досягати успіху","verb","B1","general"],
["fail","провалюватися","verb","B1","general"],
["achieve","добиватися","verb","B1","general"],
["complete","завершувати","verb","B1","general"],
["launch","запускати","verb","B1","business"],
["proceed","продовжувати","verb","B1","general"],
["delay","затримувати","verb","B1","general"],
["postpone","відкладати","verb","B1","general"],
["hurry","поспішати","verb","B1","daily life"],
["rush","мчати","verb","B1","daily life"],
["consider","думати над","verb","B1","general"],
["suppose","припускати","verb","B1","general"],
["assume","припускати","verb","B1","general"],
["realise","усвідомлювати","verb","B1","general"],
["recognise","впізнавати","verb","B1","general"],
["appreciate","цінувати","verb","B1","general"],
["respect","поважати","verb","B1","general"],
["admire","захоплюватися","verb","B1","emotions"],
["worship","боготворити","verb","B1","emotions"],
["fear","боятися","verb","B1","emotions"],
["threaten","загрожувати","verb","B1","general"],
["struggle","боротися","verb","B1","general"],
["challenge","кидати виклик","verb","B1","general"],
["compete","змагатися","verb","B1","sport"],
["perform","виступати","verb","B1","hobby"],
["entertain","розважати","verb","B1","hobby"],
["amuse","бавити","verb","B1","hobby"],
["photograph","фотографувати","verb","B1","hobby"],
["describe","описувати","verb","B1","communication"],
["explain","пояснювати","verb","B1","communication"],
["discuss","обговорювати","verb","B1","communication"],
["debate","дискутувати","verb","B1","communication"],
["argue","сперечатися","verb","B1","communication"],
["interrupt","перебивати","verb","B1","communication"],
["repeat","повторювати","verb","B1","communication"],
["rephrase","перефразовувати","verb","B1","communication"],
["clarify","уточнювати","verb","B1","communication"],
["simplify","спрощувати","verb","B1","general"],
["resolve","вирішувати (конфлікт)","verb","B1","general"],
["compromise","йти на компроміс","verb","B1","general"],
["agree","домовлятися","verb","B1","general"],
["disagree","не погоджуватися","verb","B1","general"],
["oppose","виступати проти","verb","B1","general"],
["protest","протестувати","verb","B1","general"],
["vote","голосувати","verb","B1","general"],
["elect","обирати","verb","B1","general"],
["appoint","призначати","verb","B1","work"],
["resign","подавати у відставку","verb","B1","work"],
["retire","виходити на пенсію","verb","B1","work"],
["commute","їздити на роботу","verb","B1","work"],
["contribute","робити внесок","verb","B1","general"],

// ═══════════════ MORE B1 NOUNS ═══════════════
["profession","професія","noun","B1","work"],
["payment","платіж","noun","B1","money"],
["price","ціна","noun","B1","shopping"],
["dentist","стоматолог","noun","B1","health"],
["hardware","обладнання","noun","B1","technology"],
["folder","папка","noun","B1","technology"],
["document","документ","noun","B1","technology"],
["database","база даних","noun","B1","technology"],
["virus","вірус","noun","B1","technology"],
["error","помилка","noun","B1","technology"],
["smartphone","смартфон","noun","B1","technology"],
["tablet","планшет","noun","B1","technology"],
["laptop","ноутбук","noun","B1","technology"],
["printer","принтер","noun","B1","technology"],
["ability","здатність","noun","B1","school"],
["method","метод","noun","B1","school"],
["solution","розв'язання","noun","B1","general"],
["development","розвиток","noun","B1","general"],
["improvement","поліпшення","noun","B1","general"],
["mistake","помилка","noun","B1","general"],
["argument","аргумент","noun","B1","communication"],
["debate","дискусія","noun","B1","communication"],
["conversation","розмова","noun","B1","communication"],
["speech","промова","noun","B1","communication"],
["discussion","обговорення","noun","B1","communication"],
["survey","опитування","noun","B1","communication"],
["report","звіт","noun","B1","work"],
["presentation","презентація","noun","B1","work"],
["language","мова","noun","B1","general"],
["history","історія","noun","B1","general"],
["politics","політика","noun","B1","general"],
["tour","екскурсія","noun","B1","travel"],
["souvenir","сувенір","noun","B1","travel"],
["currency","валюта","noun","B1","money"],
["attraction","визначна пам'ятка","noun","B1","travel"],
["landscape","краєвид","noun","B1","nature"],
["coast","узбережжя","noun","B1","nature"],
["harbour","гавань","noun","B1","nature"],
["temperature","температура","noun","B1","weather"],
["humidity","вологість","noun","B1","weather"],
["calorie","калорія","noun","B1","food"],
["vegetarian","вегетаріанець","noun","B1","food"],
["flavour","смак","noun","B1","food"],
["appetite","апетит","noun","B1","food"],
["exhibition","виставка","noun","B1","hobby"],
["gallery","галерея","noun","B1","hobby"],
["concert","концерт","noun","B1","hobby"],
["performance","вистава","noun","B1","hobby"],
["novel","роман","noun","B1","hobby"],
["poet","поет","noun","B1","hobby"],
["fiction","художня литература","noun","B1","hobby"],
["documentary","документальний фільм","noun","B1","hobby"],
["cartoon","мультфільм","noun","B1","hobby"],
["theatre","театр","noun","B1","hobby"],
["audience","глядачі","noun","B1","hobby"],
["character","персонаж","noun","B1","hobby"],
["plot","сюжет","noun","B1","hobby"],
["scene","сцена","noun","B1","hobby"],
["mood","настрій","noun","B1","emotions"],
["attitude","ставлення","noun","B1","emotions"],
["confidence","впевненість","noun","B1","emotions"],
["courage","мужність","noun","B1","emotions"],
["patience","терпіння","noun","B1","emotions"],
["guilt","провина","noun","B1","emotions"],
["shame","сором","noun","B1","emotions"],
["pride","гордість","noun","B1","emotions"],
["disappointment","розчарування","noun","B1","emotions"],
["excitement","хвилювання","noun","B1","emotions"],
["satisfaction","задоволення","noun","B1","emotions"],
["loneliness","самотність","noun","B1","emotions"],
["colleague","колега","noun","B1","work"],
["employee","працівник","noun","B1","work"],
["employer","роботодавець","noun","B1","work"],
["career","кар'єра","noun","B1","work"],
["salary","зарплата","noun","B1","work"],
["contract","контракт","noun","B1","work"],
["deadline","кінцевий термін","noun","B1","work"],
["meeting","нарада","noun","B1","work"],
["project","проект","noun","B1","work"],
["budget","бюджет","noun","B1","money"],
["profit","прибуток","noun","B1","money"],
["loss","збиток","noun","B1","money"],
["investment","інвестиція","noun","B1","money"],
["tax","податок","noun","B1","money"],
["loan","позика","noun","B1","money"],
["debt","борг","noun","B1","money"],
["account","рахунок","noun","B1","money"],
["discount","знижка","noun","B1","shopping"],
["advertisement","реклама","noun","B1","business"],
["brand","бренд","noun","B1","business"],
["product","продукт","noun","B1","business"],
["service","послуга","noun","B1","business"],
["customer","клієнт","noun","B1","business"],
["market","ринок","noun","B1","business"],
["competition","конкуренція","noun","B1","business"],
["company","компанія","noun","B1","business"],
["industry","галузь","noun","B1","business"],
["factory","завод","noun","B1","work"],
["disease","хвороба","noun","B1","health"],
["treatment","лікування","noun","B1","health"],
["surgery","операція","noun","B1","health"],
["symptom","симптом","noun","B1","health"],
["diagnosis","діагноз","noun","B1","health"],
["prescription","рецепт","noun","B1","health"],
["vaccine","вакцина","noun","B1","health"],
["injury","травма","noun","B1","health"],
["allergy","алергія","noun","B1","health"],
["diet","дієта","noun","B1","health"],
["vitamin","вітамін","noun","B1","health"],
["medicine","ліки","noun","B1","health"],
["pharmacy","аптека","noun","B1","health"],
["ambulance","швидка допомога","noun","B1","health"],
["nurse","медсестра","noun","B1","health"],
["appointment","прийом (до лікаря)","noun","B1","health"],
["software","програмне забезпечення","noun","B1","technology"],
["application","додаток","noun","B1","technology"],
["file","файл","noun","B1","technology"],
["update","оновлення","noun","B1","technology"],
["data","дані","noun","B1","technology"],
["network","мережа","noun","B1","technology"],
["connection","з'єднання","noun","B1","technology"],
["server","сервер","noun","B1","technology"],
["cloud","хмарне сховище","noun","B1","technology"],
["knowledge","знання","noun","B1","school"],
["skill","навичка","noun","B1","school"],
["experience","досвід","noun","B1","school"],
["research","дослідження","noun","B1","school"],
["experiment","експеримент","noun","B1","school"],
["theory","теорія","noun","B1","school"],
["result","результат","noun","B1","school"],
["problem","проблема","noun","B1","general"],
["goal","мета","noun","B1","general"],
["progress","прогрес","noun","B1","general"],
["challenge","виклик","noun","B1","general"],
["opinion","думка","noun","B1","communication"],
["interview","інтерв'ю","noun","B1","communication"],
["culture","культура","noun","B1","general"],
["tradition","традиція","noun","B1","general"],
["religion","релігія","noun","B1","general"],
["government","уряд","noun","B1","general"],
["law","закон","noun","B1","general"],
["right","право","noun","B1","general"],
["freedom","свобода","noun","B1","general"],
["society","суспільство","noun","B1","general"],
["community","спільнота","noun","B1","general"],
["citizen","громадянин","noun","B1","general"],
["population","населення","noun","B1","general"],
["generation","покоління","noun","B1","general"],
["vote","голос (на виборах)","noun","B1","general"],
["election","вибори","noun","B1","general"],
["destination","пункт призначення","noun","B1","travel"],
["luggage","багаж","noun","B1","travel"],
["passport","паспорт","noun","B1","travel"],
["visa","віза","noun","B1","travel"],
["accommodation","проживання","noun","B1","travel"],
["reservation","бронювання","noun","B1","travel"],
["schedule","розклад","noun","B1","travel"],
["border","кордон","noun","B1","travel"],
["customs","митниця","noun","B1","travel"],
["guide","гід","noun","B1","travel"],
["environment","навколишнє середовище","noun","B1","nature"],
["pollution","забруднення","noun","B1","nature"],
["climate","клімат","noun","B1","nature"],
["earthquake","землетрус","noun","B1","nature"],
["flood","повінь","noun","B1","nature"],
["drought","посуха","noun","B1","nature"],
["season","сезон","noun","B1","weather"],
["nutrition","харчування","noun","B1","food"],
["ingredient","інгредієнт","noun","B1","food"],
["recipe","рецепт","noun","B1","food"],
["portion","порція","noun","B1","food"],
// Extra B1 nouns - gaps
["commute","поїздка на роботу","noun","B1","work"],
["overtime","понаднормовий час","noun","B1","work"],
["internship","стажування","noun","B1","work"],
["promotion","підвищення","noun","B1","work"],
["resignation","відставка","noun","B1","work"],
["retirement","вихід на пенсію","noun","B1","work"],
["colleague","співробітник","noun","B1","work"],
["negotiation","переговори","noun","B1","work"],
["cooperation","співпраця","noun","B1","work"],
["application","заявка","noun","B1","work"],
["candidate","кандидат","noun","B1","work"],
["interview","співбесіда","noun","B1","work"],
["reference","рекомендація","noun","B1","work"],
["benefit","пільга","noun","B1","work"],
["pension","пенсія","noun","B1","money"],
["mortgage","іпотека","noun","B1","money"],
["insurance","страхування","noun","B1","money"],
["income","дохід","noun","B1","money"],
["expense","витрата","noun","B1","money"],
["saving","заощадження","noun","B1","money"],
["charity","благодійність","noun","B1","general"],
["donation","пожертва","noun","B1","general"],
["volunteer","волонтер","noun","B1","general"],
["campaign","кампанія","noun","B1","general"],
["protest","протест","noun","B1","general"],
["demonstration","демонстрація","noun","B1","general"],
["petition","петиція","noun","B1","general"],
["activist","активіст","noun","B1","general"],
["awareness","обізнаність","noun","B1","general"],
["policy","політика (правила)","noun","B1","general"],
["regulation","регулювання","noun","B1","general"],
["rule","правило","noun","B1","general"],
["principle","принцип","noun","B1","general"],
["value","цінність","noun","B1","general"],
["norm","норма","noun","B1","general"],
["custom","звичай","noun","B1","general"],
["habit","звичка","noun","B1","daily life"],
["routine","розпорядок дня","noun","B1","daily life"],
["lifestyle","спосіб життя","noun","B1","daily life"],
["hobby","хобі","noun","B1","hobby"],
["talent","талант","noun","B1","general"],
["passion","пристрасть","noun","B1","emotions"],
["motivation","мотивація","noun","B1","general"],
["ambition","амбіція","noun","B1","general"],
["effort","зусилля","noun","B1","general"],
["attempt","спроба","noun","B1","general"],
["failure","невдача","noun","B1","general"],
["success","успіх","noun","B1","general"],
["opportunity","можливість","noun","B1","general"],
["risk","ризик","noun","B1","general"],
["advantage","перевага","noun","B1","general"],
["disadvantage","недолік","noun","B1","general"],
["complaint","скарга","noun","B1","general"],
["compliment","компліменти","noun","B1","general"],
["criticism","критика","noun","B1","general"],
["praise","похвала","noun","B1","general"],
["reward","винагорода","noun","B1","general"],
["punishment","покарання","noun","B1","general"],
["permission","дозвіл","noun","B1","general"],
["responsibility","відповідальність","noun","B1","general"],
["duty","обов'язок","noun","B1","general"],
["obligation","зобов'язання","noun","B1","general"],
["commitment","відданість","noun","B1","general"],
["trust","довіра","noun","B1","emotions"],
["relationship","стосунки","noun","B1","family"],
["friendship","дружба","noun","B1","family"],
["partnership","партнерство","noun","B1","general"],
["marriage","шлюб","noun","B1","family"],
["divorce","розлучення","noun","B1","family"],
["anniversary","річниця","noun","B1","family"],
["ceremony","церемонія","noun","B1","general"],
["festival","фестиваль","noun","B1","hobby"],
["celebration","святкування","noun","B1","daily life"],
["invitation","запрошення","noun","B1","daily life"],
["decoration","прикраса","noun","B1","home"],
["appliance","побутова техніка","noun","B1","home"],
["furniture","меблі","noun","B1","home"],
["equipment","обладнання","noun","B1","work"],
["tool","інструмент","noun","B1","work"],
["machine","машина","noun","B1","work"],
["device","пристрій","noun","B1","technology"],
["system","система","noun","B1","general"],
["platform","платформа","noun","B1","technology"],
["feature","функція","noun","B1","technology"],
["option","варіант","noun","B1","general"],
["setting","налаштування","noun","B1","technology"],
["mode","режим","noun","B1","technology"],
["version","версія","noun","B1","technology"],
["model","модель","noun","B1","technology"],
["format","формат","noun","B1","technology"],
["link","посилання","noun","B1","technology"],
["account","обліковий запис","noun","B1","technology"],
["profile","профіль","noun","B1","technology"],
["notification","сповіщення","noun","B1","technology"],
["subscription","підписка","noun","B1","technology"],
["comment","коментар","noun","B1","technology"],
["review","відгук","noun","B1","shopping"],
["rating","рейтинг","noun","B1","general"],
["feedback","зворотній зв'язок","noun","B1","work"],
["skill set","набір навичок","noun","B1","work"],
["training","навчання","noun","B1","work"],
["workshop","майстер-клас","noun","B1","work"],
["seminar","семінар","noun","B1","school"],
["conference","конференція","noun","B1","work"],
["lecture","лекція","noun","B1","school"],
["course","курс","noun","B1","school"],
["degree","ступінь (освіта)","noun","B1","school"],
["certificate","сертифікат","noun","B1","school"],
["diploma","диплом","noun","B1","school"],
["award","нагорода","noun","B1","general"],
["prize","приз","noun","B1","general"],
["scholarship","стипендія","noun","B1","school"],
["admission","вступ","noun","B1","school"],
["graduation","випуск","noun","B1","school"],
["curriculum","навчальна програма","noun","B1","school"],
["assignment","завдання","noun","B1","school"],
["quiz","вікторина","noun","B1","school"],
["debate","дискусія","noun","B1","school"],
["essay","есе","noun","B1","school"],
["homework","домашнє завдання","noun","B1","school"],
["project","проект (шкільний)","noun","B1","school"],
["teacher","вчитель","noun","B1","school"],
["principal","директор школи","noun","B1","school"],
["laboratory","лабораторія","noun","B1","school"],
["corridor","коридор","noun","B1","school"],
["canteen","їдальня","noun","B1","food"],
["break","перерва","noun","B1","school"],
["term","семестр","noun","B1","school"],
["timetable","розклад занять","noun","B1","school"],
["subject","навчальний предмет","noun","B1","school"],
["geography","географія","noun","B1","school"],
["chemistry","хімія","noun","B1","school"],
["physics","фізика","noun","B1","school"],
["biology","біологія","noun","B1","school"],
["mathematics","математика","noun","B1","school"],
["literature","литература","noun","B1","school"],
["grammar","граматика","noun","B1","school"],
["vocabulary","словниковий запас","noun","B1","school"],

// ═══════════════ MORE B1 ADJECTIVES ═══════════════
["responsible","відповідальний","adjective","B1","general"],
["reasonable","розумний","adjective","B1","general"],
["reliable","надійний","adjective","B1","general"],
["efficient","ефективний","adjective","B1","work"],
["effective","дієвий","adjective","B1","work"],
["flexible","гнучкий","adjective","B1","work"],
["creative","творчий","adjective","B1","work"],
["professional","професійний","adjective","B1","work"],
["experienced","досвідчений","adjective","B1","work"],
["qualified","кваліфікований","adjective","B1","work"],
["motivated","мотивований","adjective","B1","work"],
["talented","талановитий","adjective","B1","general"],
["intelligent","інтелектуальний","adjective","B1","general"],
["curious","допитливий","adjective","B1","general"],
["ambitious","амбіційний","adjective","B1","general"],
["determined","рішучий","adjective","B1","general"],
["generous","щедрий","adjective","B1","general"],
["honest","чесний","adjective","B1","general"],
["loyal","відданий","adjective","B1","general"],
["cheerful","радісний","adjective","B1","emotions"],
["nervous","нервовий","adjective","B1","emotions"],
["anxious","стривожений","adjective","B1","emotions"],
["stressed","у стресі","adjective","B1","emotions"],
["depressed","пригнічений","adjective","B1","emotions"],
["confused","розгублений","adjective","B1","emotions"],
["embarrassed","збентежений","adjective","B1","emotions"],
["proud","гордий","adjective","B1","emotions"],
["jealous","ревнивий","adjective","B1","emotions"],
["bored","нудьгуючий","adjective","B1","emotions"],
["comfortable","комфортний","adjective","B1","home"],
["convenient","зручний","adjective","B1","general"],
["available","доступний","adjective","B1","general"],
["popular","популярний","adjective","B1","general"],
["useful","корисний","adjective","B1","general"],
["harmful","шкідливий","adjective","B1","health"],
["common","поширений","adjective","B1","general"],
["traditional","традиційний","adjective","B1","general"],
["modern","сучасний","adjective","B1","general"],
["local","місцевий","adjective","B1","general"],
["global","глобальний","adjective","B1","general"],
["natural","природний","adjective","B1","nature"],
["organic","органічний","adjective","B1","food"],
["expensive","дорогий","adjective","B1","shopping"],
["affordable","доступний за ціною","adjective","B1","shopping"],
["necessary","необхідний","adjective","B1","general"],
["urgent","терміновий","adjective","B1","general"],
["serious","серйозний","adjective","B1","general"],
["formal","офіційний","adjective","B1","work"],
["informal","неофіційний","adjective","B1","general"],
["significant","значний","adjective","B1","general"],
["surprising","дивовижний","adjective","B1","general"],
["optional","необов'язковий","adjective","B1","general"],
["temporary","тимчасовий","adjective","B1","general"],
["permanent","постійний","adjective","B1","general"],
["daily","щоденний","adjective","B1","time"],
["weekly","щотижневий","adjective","B1","time"],
["monthly","щомісячний","adjective","B1","time"],
["annual","щорічний","adjective","B1","time"],
["average","середній","adjective","B1","general"],
["typical","типовий","adjective","B1","general"],
["unusual","незвичний","adjective","B1","general"],
["similar","схожий","adjective","B1","general"],
["identical","ідентичний","adjective","B1","general"],
["opposite","протилежний","adjective","B1","general"],
["financial","фінансовий","adjective","B1","money"],
["economic","економічний","adjective","B1","general"],
["political","політичний","adjective","B1","general"],
["social","соціальний","adjective","B1","general"],
["cultural","культурний","adjective","B1","general"],
["educational","освітній","adjective","B1","school"],
["physical","фізичний","adjective","B1","health"],
["mental","психічний","adjective","B1","health"],
["emotional","емоційний","adjective","B1","emotions"],
["digital","цифровий","adjective","B1","technology"],
["technical","технічний","adjective","B1","technology"],
["automatic","автоматичний","adjective","B1","technology"],
["manual","ручний","adjective","B1","work"],
["practical","практичний","adjective","B1","general"],
["theoretical","теоретичний","adjective","B1","school"],
["positive","позитивний","adjective","B1","general"],
["negative","негативний","adjective","B1","general"],
["neutral","нейтральний","adjective","B1","general"],
["fair","справедливий","adjective","B1","general"],
["unfair","несправедливий","adjective","B1","general"],
["legal","законний","adjective","B1","general"],
["illegal","незаконний","adjective","B1","general"],
["safe","безпечний","adjective","B1","general"],
["dangerous","небезпечний","adjective","B1","general"],
["successful","успішний","adjective","B1","general"],
["competitive","конкурентний","adjective","B1","business"],
["environmental","екологічний","adjective","B1","nature"],
["international","міжнародний","adjective","B1","general"],
["national","національний","adjective","B1","general"],
["private","приватний","adjective","B1","general"],
["public","громадський","adjective","B1","general"],
["realistic","реалістичний","adjective","B1","general"],
["optimistic","оптимістичний","adjective","B1","emotions"],
["pessimistic","песимістичний","adjective","B1","emotions"],
["critical","критичний","adjective","B1","general"],
["logical","логічний","adjective","B1","general"],

// ═══════════════ MORE B1 ADVERBS ═══════════════
["mainly","переважно","adverb","B1","general"],
["generally","загалом","adverb","B1","general"],
["particularly","особливо","adverb","B1","general"],
["recently","нещодавно","adverb","B1","time"],
["immediately","одразу","adverb","B1","time"],
["eventually","зрештою","adverb","B1","time"],
["gradually","поступово","adverb","B1","general"],
["constantly","постійно","adverb","B1","general"],
["rarely","рідко","adverb","B1","time"],
["frequently","часто","adverb","B1","time"],
["briefly","коротко","adverb","B1","general"],
["exactly","саме","adverb","B1","general"],
["mostly","здебільшого","adverb","B1","general"],
["completely","повністю","adverb","B1","general"],
["directly","безпосередньо","adverb","B1","general"],
["properly","правильно","adverb","B1","general"],
["clearly","чітко","adverb","B1","general"],
["officially","офіційно","adverb","B1","general"],
["initially","спочатку","adverb","B1","time"],
["meanwhile","тим часом","adverb","B1","time"],
["otherwise","інакше","adverb","B1","general"],
["surprisingly","дивовижно","adverb","B1","general"],
["unfortunately","на жаль","adverb","B1","general"],
["fortunately","на щастя","adverb","B1","general"],
["certainly","звичайно","adverb","B1","general"],
["definitely","безперечно","adverb","B1","general"],
["probably","мабуть","adverb","B1","general"],
["obviously","очевидно","adverb","B1","general"],
["normally","зазвичай","adverb","B1","general"],
["especially","особливо","adverb","B1","general"],
["literally","буквально","adverb","B1","general"],
["basically","по суті","adverb","B1","general"],
["roughly","приблизно","adverb","B1","general"],
["approximately","приблизно","adverb","B1","general"],
["significantly","значно","adverb","B1","general"],
["relatively","відносно","adverb","B1","general"],
["entirely","повністю","adverb","B1","general"],
["equally","рівномірно","adverb","B1","general"],

// ═══════════════ MORE B2 VERBS ═══════════════
["implement","впроваджувати","verb","B2","work"],
["execute","виконувати","verb","B2","work"],
["assess","оцінювати (ситуацію)","verb","B2","general"],
["monitor","контролювати","verb","B2","work"],
["facilitate","сприяти","verb","B2","general"],
["coordinate","координувати","verb","B2","work"],
["integrate","інтегрувати","verb","B2","general"],
["transform","трансформувати","verb","B2","general"],
["allocate","розподіляти","verb","B2","work"],
["utilise","використовувати","verb","B2","general"],
["optimise","оптимізувати","verb","B2","work"],
["streamline","оптимізовувати процеси","verb","B2","work"],
["delegate","делегувати","verb","B2","work"],
["oversee","наглядати","verb","B2","work"],
["anticipate","передбачати","verb","B2","general"],
["forecast","прогнозувати","verb","B2","general"],
["sustain","підтримувати","verb","B2","general"],
["enhance","покращувати","verb","B2","general"],
["accelerate","прискорювати","verb","B2","general"],
["generate","генерувати","verb","B2","general"],
["derive","виводити","verb","B2","school"],
["clarify","уточнювати","verb","B2","communication"],
["elaborate","деталізувати","verb","B2","communication"],
["specify","уточнювати (деталі)","verb","B2","communication"],
["justify","обґрунтовувати","verb","B2","communication"],
["contradict","суперечити","verb","B2","communication"],
["manipulate","маніпулювати","verb","B2","general"],
["exploit","експлуатувати","verb","B2","general"],
["comply","дотримуватися","verb","B2","work"],
["regulate","регулювати","verb","B2","general"],
["restrict","обмежувати","verb","B2","general"],
["prohibit","забороняти","verb","B2","general"],
["enforce","застосовувати (закон)","verb","B2","general"],
["advocate","відстоювати","verb","B2","general"],
["challenge","оспорювати","verb","B2","general"],
["acknowledge","визнавати","verb","B2","general"],
["distinguish","розрізняти","verb","B2","general"],
["perceive","сприймати","verb","B2","general"],
["interpret","інтерпретувати","verb","B2","general"],
["identify","визначати","verb","B2","general"],
["quantify","кількісно вимірювати","verb","B2","school"],
["validate","підтверджувати","verb","B2","general"],
["verify","перевіряти (дані)","verb","B2","general"],
["scrutinize","уважно вивчати","verb","B2","general"],
["eliminate","усувати","verb","B2","general"],
["mitigate","пом'якшувати","verb","B2","general"],
["overcome","долати","verb","B2","general"],
["tackle","боротися з","verb","B2","general"],
["address","розглядати (проблему)","verb","B2","general"],
["resolve","розв'язувати","verb","B2","general"],
["outsource","аутсорсити","verb","B2","work"],
["monetize","монетизувати","verb","B2","business"],
["scale","масштабувати","verb","B2","business"],
["disrupt","порушувати (ринок)","verb","B2","business"],
["pivot","змінювати напрямок","verb","B2","business"],
["rebrand","ребрендувати","verb","B2","business"],
["incentivize","стимулювати","verb","B2","business"],
["empower","надавати повноваження","verb","B2","work"],
["depict","зображувати","verb","B2","hobby"],
["portray","описувати","verb","B2","hobby"],
["symbolise","символізувати","verb","B2","hobby"],
["characterise","характеризувати","verb","B2","general"],
["undermine","підривати","verb","B2","general"],
["reinforce","зміцнювати","verb","B2","general"],
["supplement","доповнювати","verb","B2","general"],
["compensate","компенсувати","verb","B2","general"],
["arbitrate","виступати арбітром","verb","B2","work"],
["restructure","реструктуризувати","verb","B2","work"],
["benchmark","зіставляти з еталоном","verb","B2","business"],
["restructure","реорганізовувати","verb","B2","work"],
["negotiate","проводити переговори","verb","B2","work"],
// additional B2 verbs
["infer","робити висновок","verb","B2","school"],
["deduce","виводити логічно","verb","B2","school"],
["formulate","формулювати","verb","B2","school"],
["propose","пропонувати (план)","verb","B2","general"],
["conceptualise","концептуалізувати","verb","B2","school"],
["operationalise","операціоналізувати","verb","B2","school"],
["contextualise","контекстуалізувати","verb","B2","school"],
["synthesise","синтезувати","verb","B2","school"],
["critique","критикувати","verb","B2","hobby"],
["articulate","чітко висловлювати","verb","B2","communication"],
["convey","передавати (ідею)","verb","B2","communication"],
["persuade","переконувати","verb","B2","communication"],
["coerce","примушувати","verb","B2","general"],
["intimidate","залякувати","verb","B2","general"],
["denounce","засуджувати","verb","B2","general"],
["condemn","засуджувати","verb","B2","general"],
["endorse","підтримувати (публічно)","verb","B2","general"],
["subsidize","субсидувати","verb","B2","money"],
["depreciate","знецінюватися","verb","B2","money"],
["accumulate","накопичувати","verb","B2","money"],
["diversify","диверсифікувати","verb","B2","business"],
["consolidate","консолідувати","verb","B2","business"],
["restructure","реструктурувати","verb","B2","business"],
["franchise","продавати франшизу","verb","B2","business"],
["tender","подавати тендер","verb","B2","business"],
["audit","проводити аудит","verb","B2","work"],
["deregulate","дерегулювати","verb","B2","general"],
["liberalize","лібералізувати","verb","B2","general"],
["decentralize","децентралізувати","verb","B2","general"],
["democratize","демократизувати","verb","B2","general"],
["modernize","модернізувати","verb","B2","general"],
["urbanize","урбанізувати","verb","B2","general"],
["colonize","колонізувати","verb","B2","general"],
["annexe","анексувати","verb","B2","general"],
["embargo","запроваджувати ембарго","verb","B2","general"],
["sanction","вводити санкції","verb","B2","general"],

// ═══════════════ MORE B2 NOUNS ═══════════════
["concept","концепція","noun","B2","general"],
["principle","принцип","noun","B2","general"],
["phenomenon","явище","noun","B2","general"],
["perspective","точка зору","noun","B2","general"],
["aspect","аспект","noun","B2","general"],
["factor","фактор","noun","B2","general"],
["element","елемент","noun","B2","general"],
["structure","структура","noun","B2","general"],
["framework","рамки","noun","B2","general"],
["mechanism","механізм","noun","B2","general"],
["process","процес","noun","B2","general"],
["procedure","процедура","noun","B2","general"],
["strategy","стратегія","noun","B2","general"],
["approach","підхід","noun","B2","general"],
["outcome","результат","noun","B2","general"],
["impact","вплив","noun","B2","general"],
["effect","ефект","noun","B2","general"],
["consequence","наслідок","noun","B2","general"],
["assumption","припущення","noun","B2","general"],
["hypothesis","гіпотеза","noun","B2","school"],
["evidence","докази","noun","B2","general"],
["criteria","критерії","noun","B2","general"],
["objective","мета","noun","B2","work"],
["priority","пріоритет","noun","B2","work"],
["initiative","ініціатива","noun","B2","work"],
["innovation","інновація","noun","B2","business"],
["achievement","досягнення","noun","B2","general"],
["contribution","внесок","noun","B2","general"],
["benefit","перевага","noun","B2","general"],
["advantage","переваги","noun","B2","general"],
["disadvantage","недолік","noun","B2","general"],
["obstacle","перешкода","noun","B2","general"],
["barrier","бар'єр","noun","B2","general"],
["threat","загроза","noun","B2","general"],
["conflict","конфлікт","noun","B2","general"],
["crisis","криза","noun","B2","general"],
["recession","рецесія","noun","B2","money"],
["inflation","інфляція","noun","B2","money"],
["revenue","виручка","noun","B2","business"],
["expenditure","витрати","noun","B2","money"],
["funding","фінансування","noun","B2","money"],
["grant","грант","noun","B2","money"],
["stakeholder","зацікавлена сторона","noun","B2","business"],
["shareholder","акціонер","noun","B2","business"],
["entrepreneur","підприємець","noun","B2","business"],
["executive","керівник","noun","B2","business"],
["consultant","консультант","noun","B2","work"],
["analyst","аналітик","noun","B2","work"],
["expert","експерт","noun","B2","work"],
["specialist","фахівець","noun","B2","work"],
["corporation","корпорація","noun","B2","business"],
["headquarters","штаб-квартира","noun","B2","business"],
["merger","злиття","noun","B2","business"],
["acquisition","поглинання","noun","B2","business"],
["legislation","законодавство","noun","B2","general"],
["constitution","конституція","noun","B2","general"],
["democracy","демократія","noun","B2","general"],
["reform","реформа","noun","B2","general"],
["corruption","корупція","noun","B2","general"],
["sustainability","стійкість","noun","B2","nature"],
["emission","викид","noun","B2","nature"],
["biodiversity","біорізноманіття","noun","B2","nature"],
["ecosystem","екосистема","noun","B2","nature"],
["species","вид","noun","B2","nature"],
["habitat","середовище існування","noun","B2","nature"],
["extinction","вимирання","noun","B2","nature"],
["conservation","охорона природи","noun","B2","nature"],
["welfare","добробут","noun","B2","general"],
["inequality","нерівність","noun","B2","general"],
["discrimination","дискримінація","noun","B2","general"],
["diversity","різноманітність","noun","B2","general"],
["integration","інтеграція","noun","B2","general"],
["perception","сприйняття","noun","B2","general"],
["consciousness","свідомість","noun","B2","general"],
["identity","ідентичність","noun","B2","general"],
["ideology","ідеологія","noun","B2","general"],
["institution","інститут","noun","B2","general"],
["administration","адміністрація","noun","B2","general"],
["bureaucracy","бюрократія","noun","B2","general"],
["diplomat","дипломат","noun","B2","general"],
["sovereignty","суверенітет","noun","B2","general"],
["epidemic","епідемія","noun","B2","health"],
["pandemic","пандемія","noun","B2","health"],
["immunity","імунітет","noun","B2","health"],
["metabolism","метаболізм","noun","B2","health"],
["obesity","ожиріння","noun","B2","health"],
["addiction","залежність","noun","B2","health"],
["rehabilitation","реабілітація","noun","B2","health"],
["counselling","консультування","noun","B2","health"],
["therapy","терапія","noun","B2","health"],
["hormone","гормон","noun","B2","health"],
["gene","ген","noun","B2","health"],
["cell","клітина","noun","B2","health"],
["tissue","тканина","noun","B2","health"],
["organ","орган","noun","B2","health"],
["algorithm","алгоритм","noun","B2","technology"],
["encryption","шифрування","noun","B2","technology"],
["cybersecurity","кібербезпека","noun","B2","technology"],
["artificial intelligence","штучний інтелект","noun","B2","technology"],
["machine learning","машинне навчання","noun","B2","technology"],
["bandwidth","пропускна здатність","noun","B2","technology"],
["interface","інтерфейс","noun","B2","technology"],
["prototype","прототип","noun","B2","technology"],
["deployment","розгортання","noun","B2","technology"],
["automation","автоматизація","noun","B2","technology"],
["psychology","психологія","noun","B2","school"],
["sociology","соціологія","noun","B2","school"],
["economics","економіка","noun","B2","school"],
["linguistics","лінгвістика","noun","B2","school"],
["philosophy","філософія","noun","B2","school"],
["ethics","етика","noun","B2","school"],
["methodology","методологія","noun","B2","school"],
["analysis","аналіз","noun","B2","school"],
["synthesis","синтез","noun","B2","school"],
["correlation","кореляція","noun","B2","school"],
["variable","змінна","noun","B2","school"],
["sample","вибірка","noun","B2","school"],
["statistic","статистика","noun","B2","school"],
["questionnaire","анкета","noun","B2","school"],
["bibliography","бібліографія","noun","B2","school"],
["citation","цитата","noun","B2","school"],
["abstract","анотація","noun","B2","school"],
["thesis","теза","noun","B2","school"],
["aesthetic","естетика","noun","B2","hobby"],
["symbolism","символізм","noun","B2","hobby"],
["narrative","розповідь","noun","B2","hobby"],
["genre","жанр","noun","B2","hobby"],
["interpretation","інтерпретація","noun","B2","hobby"],
["critique","критика","noun","B2","hobby"],
["composition","композиція","noun","B2","hobby"],
["installation","інсталяція","noun","B2","hobby"],
["stereotype","стереотип","noun","B2","general"],
["bias","упередженість","noun","B2","general"],
["prejudice","забобон","noun","B2","general"],
["tolerance","толерантність","noun","B2","general"],
["empathy","емпатія","noun","B2","general"],
["privilege","привілей","noun","B2","general"],
["globalization","глобалізація","noun","B2","general"],
["migration","міграція","noun","B2","general"],
["refugee","біженець","noun","B2","general"],
["mentorship","наставництво","noun","B2","work"],
["productivity","продуктивність","noun","B2","work"],
["efficiency","ефективність","noun","B2","work"],
["transparency","прозорість","noun","B2","work"],
["accountability","відповідальність (корп.)","noun","B2","work"],
["compliance","відповідність вимогам","noun","B2","work"],
["audit","аудит","noun","B2","work"],
["redundancy","скорочення штату","noun","B2","work"],
["momentum","імпульс","noun","B2","general"],
["paradigm","парадигма","noun","B2","general"],
["benchmark","еталон","noun","B2","business"],
["portfolio","портфоліо","noun","B2","work"],
["expertise","експертиза","noun","B2","work"],
["legacy","спадщина","noun","B2","general"],
["heritage","культурна спадщина","noun","B2","general"],
["folklore","фольклор","noun","B2","general"],
["mythology","міфологія","noun","B2","general"],
["metaphor","метафора","noun","B2","general"],
["irony","іронія","noun","B2","general"],
["ambiguity","двозначність","noun","B2","general"],
["contradiction","суперечність","noun","B2","general"],
["compromise","компроміс","noun","B2","general"],
["consensus","консенсус","noun","B2","general"],
["rhetoric","риторика","noun","B2","general"],
["propaganda","пропаганда","noun","B2","general"],
["censorship","цензура","noun","B2","general"],
// Extra B2 nouns
["implication","наслідок","noun","B2","general"],
["sovereignty","суверенність","noun","B2","general"],
["urbanization","урбанізація","noun","B2","general"],
["marginalization","маргіналізація","noun","B2","general"],
["infrastructure","інфраструктура","noun","B2","general"],
["monopoly","монополія","noun","B2","business"],
["oligopoly","олігополія","noun","B2","business"],
["cartel","картель","noun","B2","business"],
["subsidiary","дочірнє підприємство","noun","B2","business"],
["conglomerate","конгломерат","noun","B2","business"],
["franchise","франшиза","noun","B2","business"],
["trademark","торговельна марка","noun","B2","business"],
["patent","патент","noun","B2","business"],
["copyright","авторське право","noun","B2","business"],
["liability","зобов'язання","noun","B2","work"],
["asset","актив","noun","B2","money"],
["equity","власний капітал","noun","B2","money"],
["dividend","дивіденд","noun","B2","money"],
["portfolio","інвестиційний портфель","noun","B2","money"],
["commodity","товар","noun","B2","business"],
["tariff","тариф","noun","B2","business"],
["subsidy","субсидія","noun","B2","money"],
["deficit","дефіцит","noun","B2","money"],
["surplus","надлишок","noun","B2","money"],
["austerity","жорстка економія","noun","B2","money"],
["devaluation","девальвація","noun","B2","money"],
["cryptocurrency","криптовалюта","noun","B2","technology"],
["blockchain","блокчейн","noun","B2","technology"],
["referendum","референдум","noun","B2","general"],
["mandate","мандат","noun","B2","general"],
["coalition","коаліція","noun","B2","general"],
["opposition","опозиція","noun","B2","general"],
["lobbyist","лобіст","noun","B2","general"],
["bureaucrat","бюрократ","noun","B2","general"],
["sanction","санкція","noun","B2","general"],
["treaty","договір","noun","B2","general"],
["alliance","альянс","noun","B2","general"],
["deterrence","стримування","noun","B2","general"],
["geopolitics","геополітика","noun","B2","general"],
["archipelago","архіпелаг","noun","B2","nature"],
["peninsula","півострів","noun","B2","nature"],
["plateau","плато","noun","B2","nature"],
["glacier","льодовик","noun","B2","nature"],
["tropics","тропіки","noun","B2","nature"],
["hemisphere","півкуля","noun","B2","nature"],
["latitude","широта","noun","B2","nature"],
["longitude","довгота","noun","B2","nature"],
["altitude","висота","noun","B2","nature"],
["topography","топографія","noun","B2","nature"],
["magnetism","магнетизм","noun","B2","school"],
["thermodynamics","термодинаміка","noun","B2","school"],
["quantum","квант","noun","B2","school"],
["neuroscience","нейронаука","noun","B2","school"],
["cognition","пізнання","noun","B2","school"],
["perception","перцепція","noun","B2","school"],
["consciousness","свідомість","noun","B2","school"],
["subconscious","підсвідомість","noun","B2","school"],
["psyche","психіка","noun","B2","school"],
["trauma","травма","noun","B2","health"],
["anxiety disorder","тривожний розлад","noun","B2","health"],
["schizophrenia","шизофренія","noun","B2","health"],
["dementia","деменція","noun","B2","health"],
["prognosis","прогноз (медичний)","noun","B2","health"],
["pathology","патологія","noun","B2","health"],
["anatomy","анатомія","noun","B2","health"],
["physiology","фізіологія","noun","B2","health"],
["embryo","ембріон","noun","B2","health"],
["chromosome","хромосома","noun","B2","health"],
// B2 adjectives (second list)
["sophisticated","витончений","adjective","B2","general"],
["comprehensive","всебічний","adjective","B2","general"],
["substantial","значний","adjective","B2","general"],
["considerable","суттєвий","adjective","B2","general"],
["fundamental","фундаментальний","adjective","B2","general"],
["inherent","притаманний","adjective","B2","general"],
["explicit","явний","adjective","B2","general"],
["implicit","неявний","adjective","B2","general"],
["ambiguous","неоднозначний","adjective","B2","general"],
["straightforward","зрозумілий","adjective","B2","general"],
["controversial","суперечливий","adjective","B2","general"],
["innovative","інноваційний","adjective","B2","business"],
["strategic","стратегічний","adjective","B2","business"],
["sustainable","стійкий","adjective","B2","nature"],
["renewable","відновлюваний","adjective","B2","nature"],
["toxic","токсичний","adjective","B2","nature"],
["vulnerable","вразливий","adjective","B2","general"],
["resilient","стійкий (до труднощів)","adjective","B2","general"],
["proactive","проактивний","adjective","B2","work"],
["objective","об'єктивний","adjective","B2","general"],
["subjective","суб'єктивний","adjective","B2","general"],
["abstract","абстрактний","adjective","B2","general"],
["concrete","конкретний","adjective","B2","general"],
["empirical","емпіричний","adjective","B2","school"],
["quantitative","кількісний","adjective","B2","school"],
["qualitative","якісний","adjective","B2","school"],
["diverse","різноманітний","adjective","B2","general"],
["inclusive","інклюзивний","adjective","B2","general"],
["transparent","прозорий","adjective","B2","work"],
["accountable","підзвітний","adjective","B2","work"],
["ethical","етичний","adjective","B2","general"],
["biased","упереджений","adjective","B2","general"],
["rigorous","ретельний","adjective","B2","school"],
["thorough","ґрунтовний","adjective","B2","general"],
["meticulous","педантичний","adjective","B2","general"],
["excessive","надмірний","adjective","B2","general"],
["insufficient","недостатній","adjective","B2","general"],
["adequate","відповідний","adjective","B2","general"],
["obsolete","застарілий","adjective","B2","technology"],
["cutting-edge","передовий","adjective","B2","technology"],
["groundbreaking","новаторський","adjective","B2","general"],
["unprecedented","безпрецедентний","adjective","B2","general"],
["inevitable","неминучий","adjective","B2","general"],
["plausible","правдоподібний","adjective","B2","general"],
["feasible","здійсненний","adjective","B2","general"],
["viable","життєздатний","adjective","B2","business"],
["lucrative","вигідний","adjective","B2","business"],
["mutual","взаємний","adjective","B2","general"],
["concurrent","одночасний","adjective","B2","general"],
["subsequent","наступний","adjective","B2","general"],
["preliminary","попередній","adjective","B2","general"],
["integral","невід'ємний","adjective","B2","general"],
["marginal","незначний","adjective","B2","general"],
["acute","гострий","adjective","B2","health"],
["chronic","хронічний","adjective","B2","health"],
["infectious","інфекційний","adjective","B2","health"],
["cognitive","когнітивний","adjective","B2","health"],
["genetic","генетичний","adjective","B2","health"],
["innate","вроджений","adjective","B2","general"],
["acquired","набутий","adjective","B2","general"],
["disposable","одноразовий","adjective","B2","general"],
["renewable","поновлюваний","adjective","B2","nature"],
["degradable","такий, що розкладається","adjective","B2","nature"],
["hazardous","небезпечний","adjective","B2","general"],
["volatile","нестабільний","adjective","B2","general"],
["transparent","прозорий (метафор.)","adjective","B2","general"],
["opaque","непрозорий","adjective","B2","general"],
["provisional","тимчасовий","adjective","B2","general"],
["definitive","остаточний","adjective","B2","general"],
["autonomous","автономний","adjective","B2","general"],
["bilateral","двосторонній","adjective","B2","general"],
["multilateral","багатосторонній","adjective","B2","general"],
["unprecedented","небувалий","adjective","B2","general"],
["imminent","неминучий (близький)","adjective","B2","general"],
["obsolete","застарілий (устар.)","adjective","B2","technology"],
["redundant","зайвий","adjective","B2","work"],
["contingent","залежний від умов","adjective","B2","general"],
["cumulative","кумулятивний","adjective","B2","general"],
["aggregate","сукупний","adjective","B2","general"],
["overarching","всеохопний","adjective","B2","general"],
["underlying","основний","adjective","B2","general"],
["unprecedented","унікальний","adjective","B2","general"],
// B2 adverbs
["consequently","отже","adverb","B2","general"],
["nevertheless","тим не менш","adverb","B2","general"],
["furthermore","крім того","adverb","B2","general"],
["moreover","до того ж","adverb","B2","general"],
["however","проте","adverb","B2","general"],
["therefore","тому","adverb","B2","general"],
["thus","таким чином","adverb","B2","general"],
["hence","звідси","adverb","B2","general"],
["likewise","так само","adverb","B2","general"],
["conversely","навпаки","adverb","B2","general"],
["arguably","мабуть","adverb","B2","general"],
["notably","зокрема","adverb","B2","general"],
["extensively","широко","adverb","B2","general"],
["substantially","суттєво","adverb","B2","general"],
["consistently","послідовно","adverb","B2","general"],
["predominantly","переважно","adverb","B2","general"],
["simultaneously","одночасно","adverb","B2","general"],
["inevitably","неминуче","adverb","B2","general"],
["accordingly","відповідно","adverb","B2","general"],
["deliberately","навмисно","adverb","B2","general"],
["explicitly","явно","adverb","B2","general"],
["inherently","по суті","adverb","B2","general"],
["ultimately","в кінцевому підсумку","adverb","B2","general"],
["presumably","вочевидь","adverb","B2","general"],
["technically","технічно","adverb","B2","general"],
["systematically","систематично","adverb","B2","general"],
["comprehensively","всебічно","adverb","B2","general"],
["predominantly","головним чином","adverb","B2","general"],
["inherently","за своєю суттю","adverb","B2","general"],
["retrospectively","ретроспективно","adverb","B2","general"],
["prospectively","перспективно","adverb","B2","general"],
];

// ── DEDUP & VALIDATE ─────────────────────────────────────────────────────────
const seen = new Set();
const validPos = new Set(["verb","noun","adjective","adverb","number","conjunction","preposition","phrase"]);
const validLevels = new Set(["A2","B1","B2"]);

const newWords = [];
let dupExist=0, dupInternal=0, badSchema=0;

for (const [en,ua,pos,level,topic] of RAW2) {
  const key = en.toLowerCase();
  if (existSet.has(key))       { dupExist++; continue; }
  if (seen.has(key))           { dupInternal++; continue; }
  if (!validPos.has(pos))      { badSchema++; console.warn('Bad pos:',en,pos); continue; }
  if (!validLevels.has(level)) { badSchema++; console.warn('Bad level:',en,level); continue; }
  if (!en||!ua||!topic)        { badSchema++; console.warn('Missing field:',en); continue; }
  seen.add(key);
  newWords.push({en,ua,pos,level,topic});
}

console.log(`Candidates: ${RAW2.length}`);
console.log(`Skipped (exist): ${dupExist}`);
console.log(`Skipped (internal dup): ${dupInternal}`);
console.log(`Skipped (bad schema): ${badSchema}`);
console.log(`New valid entries: ${newWords.length}`);

const byLevel={}, byPos={};
newWords.forEach(w => {
  byLevel[w.level]=(byLevel[w.level]||0)+1;
  byPos[w.pos]=(byPos[w.pos]||0)+1;
});
console.log('New by level:', byLevel);
console.log('New by pos:', byPos);

fs.writeFileSync('./new_batch2.json', JSON.stringify(newWords, null, 2));
console.log('Wrote new_batch2.json');
