'use strict';
const fs = require('fs');

const existing  = JSON.parse(fs.readFileSync('./words.json', 'utf8'));
const batch2    = JSON.parse(fs.readFileSync('./new_batch2.json', 'utf8'));
// Also load batch1 from gen_words.js output (it didn't save, so reload from file)
const existSet  = new Set([
  ...existing.map(w=>w.en.toLowerCase()),
  ...batch2.map(w=>w.en.toLowerCase()),
]);

// Load what batch1 (the valid 530) would have produced — we need to recreate its output
// Since gen_words.js failed before saving, we just run batch1 logic inline here
const RAW1_KEPT = [
"shoulder","elbow","knee","ankle","thumb","toe","chin","cheek","forehead","wrist","nail","lip","tooth","throat","chest","stomach","heel","palm","bone","skin","blood","muscle",
"pants","boot","sock","scarf","glove","suit","belt","pocket","sleeve","collar","zip","cap","swimsuit","uniform",
"pepper","oil","lemon","grape","strawberry","carrot","mushroom","pear","cherry","plum","watermelon","honey","jam","flour","cream","yogurt","noodle","snack","dessert","meal","dish","sausage","ham","bacon","bean","pea","corn","cabbage","cucumber","garlic","onion","pumpkin","peach","melon",
"ceiling","carpet","shelf","curtain","tap","shower","toilet","lamp","mirror","sofa","desk","pot","pan","oven","microwave","soap","towel","lock","lift","iron","vacuum cleaner","washing machine","plug","switch","bin","drawer","pillow","blanket","sheet","armchair","wardrobe",
"library","cinema","museum","church","bridge","building","gym","supermarket","post office","stadium","flat","fountain","square","port",
"lake","island","star","moon","earth","sand","fog","ice","storm","rainbow","wave","cave","valley","hill","cliff",
"duck","sheep","rabbit","bear","lion","tiger","elephant","monkey","cow","pig","horse","wolf","fox","snake","butterfly","bee","frog","deer","eagle","parrot",
"bike","truck","ferry","helicopter","subway",
"umbrella","wallet","ring","necklace","magazine","stamp","envelope","alarm","shape","photo","picture","coin","receipt","address","cable","battery",
"word","sentence","story","paragraph","subject","lesson","exam","grade","dictionary","textbook","blackboard","pencil","ruler","scissors","glue",
"game","song","music","team","ball","sport","player","match","score","goal","race","club","instrument",
"baby","neighbor","guest","crowd",
"jump","run","sit","stand","fall","carry","hold","bring","move","turn","push","pull","drop","pack","meet","visit","play","sing","dance","paint","swim","drive","fly","climb","smile","laugh","cry","miss","wear","cut","break","fix","build","grow","plant","hang","heat","cool","pour","mix","boil","fry","bake","save","lose","win","practice","hurry","relax","return","arrive","enter","exit","knock","point","touch","catch","throw","lift","bite","kick","rent","borrow","lend","choose","collect","invite","celebrate","surprise","promise","agree","refuse","follow","check","ride","share","earn","spend","suggest",
"tall","thin","fat","cool","sour","salty","spicy","delicious","hungry","thirsty","loud","closed","same","sunny","cloudy","rainy","windy","snowy","foggy","wet","wide","narrow","deep","shallow","round","straight","bright","boring","funny","cute","ugly","strange","perfect","terrible","wonderful","amazing","delicate","flat","frozen","fresh","raw","cooked","ripe","broken","lost","alone","clever","lazy","polite","rude","shy","brave","early","late","sharp",
"slowly","quickly","quietly","loudly","carefully","suddenly","together","outside","inside","upstairs","downstairs","enough","away","ahead","instead",
];
const batch1Set = new Set(RAW1_KEPT.map(w=>w.toLowerCase()));
// Add batch1 to existSet
for (const w of batch1Set) existSet.add(w);

console.log('Total excluded so far:', existSet.size);

const RAW3 = [
// ── ADDITIONAL A2 WORDS (need ~57 more) ──────────────────────────────────
// a2 nouns - more basic
["map","карта","noun","A2","travel"],
["ticket","квиток","noun","A2","travel"],
["passport","паспорт","noun","A2","travel"],
["hotel","готель","noun","A2","travel"],
["gift","подарунок","noun","A2","daily life"],
["toy","іграшка","noun","A2","hobby"],
["pet","домашній улюбленець","noun","A2","animals"],
["plant","рослина","noun","A2","nature"],
["seed","насіння","noun","A2","nature"],
["root","корінь","noun","A2","nature"],
["branch","гілка","noun","A2","nature"],
["leaf","листок","noun","A2","nature"],
["fruit","фрукт","noun","A2","food"],
["vegetable","овоч","noun","A2","food"],
["pocket money","кишенькові гроші","noun","A2","money"],
["corner","кут","noun","A2","general"],
["edge","край","noun","A2","general"],
["middle","середина","noun","A2","general"],
["side","бік","noun","A2","general"],
["size","розмір","noun","A2","general"],
["weight","вага","noun","A2","general"],
["height","зріст","noun","A2","general"],
["length","довжина","noun","A2","general"],
["speed","швидкість","noun","A2","general"],
["direction","напрямок","noun","A2","general"],
["distance","відстань","noun","A2","general"],
["sound","звук","noun","A2","general"],
["noise","шум","noun","A2","general"],
["light","світло","noun","A2","general"],
["shadow","тінь","noun","A2","general"],
["smell","запах","noun","A2","general"],
["taste","смак","noun","A2","food"],
["touch","дотик","noun","A2","general"],
["sport","вид спорту","noun","A2","sport"],
["exercise","вправа","noun","A2","sport"],
["hobby","хобі","noun","A2","hobby"],
["park","парк","noun","A2","places"],
["beach","пляж","noun","A2","places"],
["airport","аеропорт","noun","A2","transport"],
["river","річка","noun","A2","nature"],
["mountain","гора","noun","A2","nature"],
["sea","море","noun","A2","nature"],
["forest","ліс","noun","A2","nature"],
["sky","небо","noun","A2","nature"],
["sun","сонце","noun","A2","nature"],
["fire","вогонь","noun","A2","nature"],
["water","вода","noun","A2","nature"],
["stone","камінь","noun","A2","nature"],
["grass","трава","noun","A2","nature"],
["flower","квітка","noun","A2","nature"],
["tree","дерево","noun","A2","nature"],
["wind","вітер","noun","A2","weather"],
["rain","дощ","noun","A2","weather"],
["snow","сніг","noun","A2","weather"],
["cloud","хмара","noun","A2","weather"],
["colour","колір","noun","A2","general"],
["dog","собака","noun","A2","animals"],
["cat","кіт","noun","A2","animals"],
["bird","птах","noun","A2","animals"],
["fish","риба","noun","A2","animals"],
["spider","павук","noun","A2","animals"],
["ant","мураха","noun","A2","animals"],
["school","школа","noun","A2","school"],
["hospital","лікарня","noun","A2","health"],
["bank","банк","noun","A2","money"],
["shop","магазин","noun","A2","shopping"],
["road","дорога","noun","A2","places"],
["street","вулиця","noun","A2","places"],
["number","число","noun","A2","numbers"],
["letter","літера","noun","A2","school"],
["box","коробка","noun","A2","general"],
["bag","сумка","noun","A2","general"],
["bottle","пляшка","noun","A2","general"],
["glass","склянка","noun","A2","general"],
["cup","чашка","noun","A2","general"],
["plate","тарілка","noun","A2","food"],
["fork","вилка","noun","A2","food"],
["knife","ніж","noun","A2","food"],
["spoon","ложка","noun","A2","food"],
["pen","ручка","noun","A2","school"],
["book","книга","noun","A2","school"],
["paper","папір","noun","A2","school"],
["chair","стілець","noun","A2","home"],
["table","стіл","noun","A2","home"],
["bed","ліжко","noun","A2","home"],
["door","двері","noun","A2","home"],
["window","вікно","noun","A2","home"],
["floor","підлога","noun","A2","home"],
["wall","стіна","noun","A2","home"],
["roof","дах","noun","A2","home"],
["kitchen","кухня","noun","A2","home"],
["bathroom","ванна кімната","noun","A2","home"],
["bedroom","спальня","noun","A2","home"],
["garden","сад","noun","A2","home"],
["key","ключ","noun","A2","home"],
["stairs","сходи","noun","A2","home"],
// a2 verbs not yet covered
["cook","готувати","verb","A2","food"],
["eat","їсти","verb","A2","food"],
["drink","пити","verb","A2","food"],
["sleep","спати","verb","A2","daily life"],
["wake","прокидатися","verb","A2","daily life"],
["wash","митися","verb","A2","daily life"],
["clean","прибирати","verb","A2","home"],
["open","відкривати","verb","A2","daily life"],
["close","закривати","verb","A2","daily life"],
["start","починати","verb","A2","general"],
["finish","закінчувати","verb","A2","general"],
["stop","зупинятися","verb","A2","general"],
["wait","чекати","verb","A2","daily life"],
["look","дивитися","verb","A2","general"],
["see","бачити","verb","A2","general"],
["hear","чути","verb","A2","general"],
["listen","слухати","verb","A2","general"],
["read","читати","verb","A2","school"],
["write","писати","verb","A2","school"],
["draw","малювати","verb","A2","hobby"],
["say","говорити","verb","A2","communication"],
["tell","розповідати","verb","A2","communication"],
["ask","запитувати","verb","A2","communication"],
["answer","відповідати","verb","A2","communication"],
["know","знати","verb","A2","general"],
["think","думати","verb","A2","general"],
["want","хотіти","verb","A2","general"],
["need","потребувати","verb","A2","general"],
["try","пробувати","verb","A2","general"],
["like","подобатися","verb","A2","general"],
["find","знаходити","verb","A2","general"],
["show","показувати","verb","A2","general"],
["call","телефонувати","verb","A2","communication"],
["pay","платити","verb","A2","money"],
["buy","купувати","verb","A2","shopping"],
["sell","продавати","verb","A2","shopping"],
["use","використовувати","verb","A2","general"],
["help","допомагати","verb","A2","general"],
["give","давати","verb","A2","general"],
["take","брати","verb","A2","general"],
["put","класти","verb","A2","general"],
["get","отримувати","verb","A2","general"],
["go","йти","verb","A2","daily life"],
["come","приходити","verb","A2","daily life"],
["live","жити","verb","A2","daily life"],
["stay","залишатися","verb","A2","daily life"],
["leave","виходити","verb","A2","daily life"],
["speak","говорити","verb","A2","communication"],
["talk","розмовляти","verb","A2","communication"],
["understand","розуміти","verb","A2","general"],
["remember","пам'ятати","verb","A2","general"],
["forget","забувати","verb","A2","general"],
["learn","вчитися","verb","A2","school"],
["teach","навчати","verb","A2","school"],
["work","працювати","verb","A2","work"],
["play","грати","verb","A2","hobby"],
["make","робити","verb","A2","general"],
["do","виконувати","verb","A2","general"],
["love","любити","verb","A2","emotions"],
["hate","ненавидіти","verb","A2","emotions"],
["feel","відчувати","verb","A2","emotions"],
// A2 adjectives
["good","добрий","adjective","A2","general"],
["bad","поганий","adjective","A2","general"],
["big","великий","adjective","A2","general"],
["small","маленький","adjective","A2","general"],
["long","довгий","adjective","A2","general"],
["short","короткий","adjective","A2","general"],
["fast","швидкий","adjective","A2","general"],
["slow","повільний","adjective","A2","general"],
["easy","легкий","adjective","A2","general"],
["hard","важкий","adjective","A2","general"],
["hot","гарячий","adjective","A2","general"],
["cold","холодний","adjective","A2","general"],
["warm","теплий","adjective","A2","general"],
["soft","м'який","adjective","A2","general"],
["loud","гучний","adjective","A2","general"],
["quiet","тихий","adjective","A2","general"],
["dark","темний","adjective","A2","general"],
["light","легкий (вага)","adjective","A2","general"],
["sweet","солодкий","adjective","A2","food"],
["clean","чистий","adjective","A2","general"],
["dirty","брудний","adjective","A2","general"],
["hungry","голодний","adjective","A2","health"],
["tired","втомлений","adjective","A2","health"],
["sick","хворий","adjective","A2","health"],
["healthy","здоровий","adjective","A2","health"],
["happy","щасливий","adjective","A2","emotions"],
["sad","сумний","adjective","A2","emotions"],
["angry","злий","adjective","A2","emotions"],
["scared","наляканий","adjective","A2","emotions"],
["surprised","здивований","adjective","A2","emotions"],
["excited","схвильований","adjective","A2","emotions"],
["bored","нудьгуючий","adjective","A2","emotions"],
["young","молодий","adjective","A2","general"],
["old","старий","adjective","A2","general"],
["new","новий","adjective","A2","general"],
["free","вільний","adjective","A2","general"],
["full","повний","adjective","A2","general"],
["empty","порожній","adjective","A2","general"],
["open","відкритий","adjective","A2","general"],
["right","правий","adjective","A2","general"],
["wrong","неправильний","adjective","A2","general"],
["true","правдивий","adjective","A2","general"],
["false","хибний","adjective","A2","general"],
["possible","можливий","adjective","A2","general"],
["different","різний","adjective","A2","general"],
["important","важливий","adjective","A2","general"],
["interesting","цікавий","adjective","A2","general"],
["beautiful","гарний","adjective","A2","general"],
["nice","приємний","adjective","A2","general"],
// A2 adverbs
["here","тут","adverb","A2","general"],
["there","там","adverb","A2","general"],
["now","зараз","adverb","A2","time"],
["then","потім","adverb","A2","time"],
["soon","скоро","adverb","A2","time"],
["late","пізно","adverb","A2","time"],
["early","рано","adverb","A2","time"],
["almost","майже","adverb","A2","general"],
["just","саме","adverb","A2","general"],
["very","дуже","adverb","A2","general"],
["really","справді","adverb","A2","general"],
["quite","досить","adverb","A2","general"],
["also","також","adverb","A2","general"],
["again","знову","adverb","A2","general"],
["still","ще","adverb","A2","general"],
["already","вже","adverb","A2","general"],
["never","ніколи","adverb","A2","time"],
["always","завжди","adverb","A2","time"],
["usually","зазвичай","adverb","A2","time"],
["often","часто","adverb","A2","time"],
["sometimes","іноді","adverb","A2","time"],
["seldom","рідко","adverb","A2","time"],
["maybe","можливо","adverb","A2","general"],
["perhaps","можливо","adverb","A2","general"],
["too","занадто","adverb","A2","general"],
["so","так","adverb","A2","general"],
["well","добре","adverb","A2","general"],
["hard","важко","adverb","A2","general"],
["long","довго","adverb","A2","time"],
["far","далеко","adverb","A2","general"],
["near","близько","adverb","A2","general"],
["home","додому","adverb","A2","daily life"],
["everywhere","скрізь","adverb","A2","general"],
["somewhere","десь","adverb","A2","general"],
["nowhere","ніде","adverb","A2","general"],
["yet","ще (не)","adverb","A2","time"],
["only","тільки","adverb","A2","general"],

// ── ADDITIONAL B1 WORDS ─────────────────────────────────────────────────────
["penalty","штраф","noun","B1","sport"],
["referee","суддя","noun","B1","sport"],
["championship","чемпіонат","noun","B1","sport"],
["tournament","турнір","noun","B1","sport"],
["fitness","фізична форма","noun","B1","sport"],
["training","тренування","noun","B1","sport"],
["coach","тренер","noun","B1","sport"],
["athlete","спортсмен","noun","B1","sport"],
["marathon","марафон","noun","B1","sport"],
["competition","змагання","noun","B1","sport"],
["swimmer","плавець","noun","B1","sport"],
["cyclist","велосипедист","noun","B1","sport"],
["runner","бігун","noun","B1","sport"],
["award","нагорода","noun","B1","general"],
["prize","приз","noun","B1","general"],
["donation","пожертва","noun","B1","general"],
["charity","благодійність","noun","B1","general"],
["volunteer","волонтер","noun","B1","general"],
["campaign","кампанія","noun","B1","general"],
["protest","протест","noun","B1","general"],
["petition","петиція","noun","B1","general"],
["activist","активіст","noun","B1","general"],
["policy","правила","noun","B1","general"],
["rule","правило","noun","B1","general"],
["value","цінність","noun","B1","general"],
["norm","норма","noun","B1","general"],
["custom","звичай","noun","B1","general"],
["habit","звичка","noun","B1","daily life"],
["routine","розпорядок дня","noun","B1","daily life"],
["lifestyle","спосіб життя","noun","B1","daily life"],
["talent","талант","noun","B1","general"],
["passion","пристрасть","noun","B1","emotions"],
["motivation","мотивація","noun","B1","general"],
["ambition","амбіція","noun","B1","general"],
["effort","зусилля","noun","B1","general"],
["attempt","спроба","noun","B1","general"],
["failure","невдача","noun","B1","general"],
["success","успіх","noun","B1","general"],
["complaint","скарга","noun","B1","general"],
["compliment","компліменти","noun","B1","general"],
["praise","похвала","noun","B1","general"],
["reward","винагорода","noun","B1","general"],
["punishment","покарання","noun","B1","general"],
["permission","дозвіл","noun","B1","general"],
["duty","обов'язок","noun","B1","general"],
["obligation","зобов'язання","noun","B1","general"],
["commitment","відданість","noun","B1","general"],
["trust","довіра","noun","B1","emotions"],
["relationship","стосунки","noun","B1","family"],
["friendship","дружба","noun","B1","family"],
["marriage","шлюб","noun","B1","family"],
["divorce","розлучення","noun","B1","family"],
["anniversary","річниця","noun","B1","family"],
["ceremony","церемонія","noun","B1","general"],
["festival","фестиваль","noun","B1","hobby"],
["celebration","святкування","noun","B1","daily life"],
["invitation","запрошення","noun","B1","daily life"],
["decoration","прикраса","noun","B1","home"],
["appliance","побутова техніка","noun","B1","home"],
["equipment","обладнання","noun","B1","work"],
["tool","інструмент","noun","B1","work"],
["machine","машина","noun","B1","work"],
["device","пристрій","noun","B1","technology"],
["system","система","noun","B1","general"],
["feature","функція","noun","B1","technology"],
["option","варіант","noun","B1","general"],
["setting","налаштування","noun","B1","technology"],
["mode","режим","noun","B1","technology"],
["version","версія","noun","B1","technology"],
["link","посилання","noun","B1","technology"],
["profile","профіль","noun","B1","technology"],
["notification","сповіщення","noun","B1","technology"],
["subscription","підписка","noun","B1","technology"],
["comment","коментар","noun","B1","technology"],
["rating","рейтинг","noun","B1","general"],
["feedback","зворотній зв'язок","noun","B1","work"],
["training","навчання","noun","B1","work"],
["workshop","майстер-клас","noun","B1","work"],
["seminar","семінар","noun","B1","school"],
["conference","конференція","noun","B1","work"],
["lecture","лекція","noun","B1","school"],
["course","курс","noun","B1","school"],
["degree","ступінь (освіта)","noun","B1","school"],
["certificate","сертифікат","noun","B1","school"],
["diploma","диплом","noun","B1","school"],
["scholarship","стипендія","noun","B1","school"],
["admission","вступ","noun","B1","school"],
["graduation","випуск","noun","B1","school"],
["curriculum","навчальна програма","noun","B1","school"],
["assignment","завдання","noun","B1","school"],
["quiz","вікторина","noun","B1","school"],
["essay","есе","noun","B1","school"],
["homework","домашнє завдання","noun","B1","school"],
["principal","директор школи","noun","B1","school"],
["laboratory","лабораторія","noun","B1","school"],
["corridor","коридор","noun","B1","school"],
["canteen","їдальня","noun","B1","food"],
["break","перерва","noun","B1","school"],
["term","семестр","noun","B1","school"],
["timetable","розклад занять","noun","B1","school"],
["geography","географія","noun","B1","school"],
["chemistry","хімія","noun","B1","school"],
["physics","фізика","noun","B1","school"],
["biology","біологія","noun","B1","school"],
["mathematics","математика","noun","B1","school"],
["literature","литература","noun","B1","school"],
["grammar","граматика","noun","B1","school"],
["vocabulary","словниковий запас","noun","B1","school"],
["pension","пенсія","noun","B1","money"],
["mortgage","іпотека","noun","B1","money"],
["insurance","страхування","noun","B1","money"],
["income","дохід","noun","B1","money"],
["expense","витрата","noun","B1","money"],
["saving","заощадження","noun","B1","money"],
["overtime","понаднормовий час","noun","B1","work"],
["internship","стажування","noun","B1","work"],
["promotion","підвищення","noun","B1","work"],
["resignation","відставка","noun","B1","work"],
["retirement","вихід на пенсію","noun","B1","work"],
["negotiation","переговори","noun","B1","work"],
["cooperation","співпраця","noun","B1","work"],
["reference","рекомендація (для роботи)","noun","B1","work"],
["commute","поїздка на роботу","noun","B1","work"],
// B1 verbs more
["commute","їздити на роботу","verb","B1","work"],
["contribute","робити внесок","verb","B1","general"],
["assist","допомагати","verb","B1","general"],
["adapt","адаптуватися","verb","B1","general"],
["adjust","коригувати","verb","B1","general"],
["respond","відповідати","verb","B1","communication"],
["react","реагувати","verb","B1","general"],
["handle","поводитися з","verb","B1","general"],
["obtain","отримувати","verb","B1","general"],
["retain","зберігати","verb","B1","general"],
["maintain","підтримувати (рівень)","verb","B1","general"],
["establish","встановлювати","verb","B1","general"],
["found","засновувати","verb","B1","general"],
["expand","розширювати","verb","B1","general"],
["promote","просувати","verb","B1","work"],
["transfer","передавати","verb","B1","general"],
["exchange","обмінювати","verb","B1","general"],
["combine","поєднувати","verb","B1","general"],
["separate","роз'єднувати","verb","B1","general"],
["replace","замінювати","verb","B1","general"],
["remove","усувати","verb","B1","general"],
["include","включати","verb","B1","general"],
["exclude","виключати","verb","B1","general"],
["rely","покладатися","verb","B1","general"],
["relate","відноситися","verb","B1","general"],
["affect","впливати на","verb","B1","general"],
["involve","залучати","verb","B1","general"],
["ensure","забезпечувати","verb","B1","general"],
["indicate","вказувати","verb","B1","general"],
["argue","стверджувати","verb","B1","communication"],
["claim","заявляти","verb","B1","communication"],
["prove","доводити","verb","B1","general"],
["represent","представляти","verb","B1","general"],
["reflect","відображати","verb","B1","general"],
["display","показувати","verb","B1","general"],
["calculate","обчислювати","verb","B1","school"],
["estimate","оцінювати (кількість)","verb","B1","general"],
["predict","передбачати","verb","B1","general"],
["observe","спостерігати","verb","B1","general"],
["record","записувати","verb","B1","general"],
["summarize","підсумовувати","verb","B1","school"],
["quote","цитувати","verb","B1","school"],
["refer","посилатися","verb","B1","school"],
["practise","практикувати","verb","B1","school"],
["revise","повторювати (матеріал)","verb","B1","school"],
["concentrate","зосереджуватися","verb","B1","school"],
["focus","фокусуватися","verb","B1","general"],
["intend","мати намір","verb","B1","general"],
["aim","прагнути","verb","B1","general"],
["attempt","намагатися","verb","B1","general"],
["succeed","досягати успіху","verb","B1","general"],
["fail","провалюватися","verb","B1","general"],
["complete","завершувати","verb","B1","general"],
["proceed","продовжувати","verb","B1","general"],
["delay","затримувати","verb","B1","general"],
["postpone","відкладати","verb","B1","general"],
["rush","мчати","verb","B1","daily life"],
["suppose","припускати","verb","B1","general"],
["assume","припускати","verb","B1","general"],
["realise","усвідомлювати","verb","B1","general"],
["recognise","впізнавати","verb","B1","general"],
["appreciate","цінувати","verb","B1","general"],
["respect","поважати","verb","B1","general"],
["admire","захоплюватися","verb","B1","emotions"],
["fear","боятися","verb","B1","emotions"],
["threaten","загрожувати","verb","B1","general"],
["struggle","боротися","verb","B1","general"],
["compete","змагатися","verb","B1","sport"],
["perform","виступати","verb","B1","hobby"],
["entertain","розважати","verb","B1","hobby"],
["photograph","фотографувати","verb","B1","hobby"],
["describe","описувати","verb","B1","communication"],
["discuss","обговорювати","verb","B1","communication"],
["interrupt","перебивати","verb","B1","communication"],
["repeat","повторювати","verb","B1","communication"],
["rephrase","перефразовувати","verb","B1","communication"],
["simplify","спрощувати","verb","B1","general"],
["compromise","йти на компроміс","verb","B1","general"],
["disagree","не погоджуватися","verb","B1","general"],
["oppose","виступати проти","verb","B1","general"],
["protest","протестувати","verb","B1","general"],
["vote","голосувати","verb","B1","general"],
["elect","обирати","verb","B1","general"],
["appoint","призначати","verb","B1","work"],
["resign","подавати у відставку","verb","B1","work"],
["retire","виходити на пенсію","verb","B1","work"],
["submit","подавати","verb","B1","school"],
["register","реєструватися","verb","B1","general"],

// ── ADDITIONAL B2 WORDS ─────────────────────────────────────────────────────
["monopoly","монополія","noun","B2","business"],
["subsidiary","дочірнє підприємство","noun","B2","business"],
["conglomerate","конгломерат","noun","B2","business"],
["trademark","торговельна марка","noun","B2","business"],
["patent","патент","noun","B2","business"],
["copyright","авторське право","noun","B2","business"],
["asset","актив","noun","B2","money"],
["equity","власний капітал","noun","B2","money"],
["dividend","дивіденд","noun","B2","money"],
["commodity","товар","noun","B2","business"],
["tariff","тариф","noun","B2","business"],
["subsidy","субсидія","noun","B2","money"],
["deficit","дефіцит","noun","B2","money"],
["surplus","надлишок","noun","B2","money"],
["austerity","жорстка економія","noun","B2","money"],
["devaluation","девальвація","noun","B2","money"],
["cryptocurrency","криптовалюта","noun","B2","technology"],
["blockchain","блокчейн","noun","B2","technology"],
["referendum","референдум","noun","B2","general"],
["mandate","мандат","noun","B2","general"],
["coalition","коаліція","noun","B2","general"],
["opposition","опозиція","noun","B2","general"],
["lobbyist","лобіст","noun","B2","general"],
["sanction","санкція","noun","B2","general"],
["treaty","договір","noun","B2","general"],
["alliance","альянс","noun","B2","general"],
["geopolitics","геополітика","noun","B2","general"],
["archipelago","архіпелаг","noun","B2","nature"],
["peninsula","півострів","noun","B2","nature"],
["plateau","плато","noun","B2","nature"],
["glacier","льодовик","noun","B2","nature"],
["hemisphere","півкуля","noun","B2","nature"],
["latitude","широта","noun","B2","nature"],
["longitude","довгота","noun","B2","nature"],
["altitude","висота","noun","B2","nature"],
["topography","топографія","noun","B2","nature"],
["neuroscience","нейронаука","noun","B2","school"],
["cognition","пізнання","noun","B2","school"],
["subconscious","підсвідомість","noun","B2","school"],
["psyche","психіка","noun","B2","school"],
["prognosis","прогноз (медичний)","noun","B2","health"],
["pathology","патологія","noun","B2","health"],
["anatomy","анатомія","noun","B2","health"],
["physiology","фізіологія","noun","B2","health"],
["chromosome","хромосома","noun","B2","health"],
["entrepreneurship","підприємництво","noun","B2","business"],
["franchise","франшиза","noun","B2","business"],
["liability","зобов'язання","noun","B2","work"],
["bureaucrat","бюрократ","noun","B2","general"],
["deterrence","стримування","noun","B2","general"],
["urbanization","урбанізація","noun","B2","general"],
["infrastructure","інфраструктура","noun","B2","general"],
["peer review","рецензування","noun","B2","school"],
["medium","засіб (мистецтва)","noun","B2","hobby"],
["implication","наслідок (логічний)","noun","B2","general"],
["dialogue","діалог","noun","B2","general"],
// B2 verbs additional
["infer","робити висновок","verb","B2","school"],
["deduce","виводити логічно","verb","B2","school"],
["formulate","формулювати","verb","B2","school"],
["propose","пропонувати (план)","verb","B2","general"],
["synthesise","синтезувати","verb","B2","school"],
["critique","критикувати","verb","B2","hobby"],
["articulate","чітко висловлювати","verb","B2","communication"],
["convey","передавати (ідею)","verb","B2","communication"],
["persuade","переконувати","verb","B2","communication"],
["coerce","примушувати","verb","B2","general"],
["intimidate","залякувати","verb","B2","general"],
["denounce","засуджувати","verb","B2","general"],
["endorse","підтримувати (публічно)","verb","B2","general"],
["subsidize","субсидувати","verb","B2","money"],
["depreciate","знецінюватися","verb","B2","money"],
["accumulate","накопичувати","verb","B2","money"],
["franchise","продавати франшизу","verb","B2","business"],
["tender","подавати тендер","verb","B2","business"],
["deregulate","дерегулювати","verb","B2","general"],
["liberalize","лібералізувати","verb","B2","general"],
["decentralize","децентралізувати","verb","B2","general"],
["democratize","демократизувати","verb","B2","general"],
["modernize","модернізувати","verb","B2","general"],
["colonize","колонізувати","verb","B2","general"],
["sanction","вводити санкції","verb","B2","general"],
["conceptualise","концептуалізувати","verb","B2","school"],
["contextualise","контекстуалізувати","verb","B2","school"],
// B2 adjectives additional
["innate","вроджений","adjective","B2","general"],
["acquired","набутий","adjective","B2","general"],
["disposable","одноразовий","adjective","B2","general"],
["degradable","такий, що розкладається","adjective","B2","nature"],
["hazardous","небезпечний","adjective","B2","general"],
["volatile","нестабільний","adjective","B2","general"],
["opaque","непрозорий","adjective","B2","general"],
["provisional","тимчасовий","adjective","B2","general"],
["definitive","остаточний","adjective","B2","general"],
["autonomous","автономний","adjective","B2","general"],
["bilateral","двосторонній","adjective","B2","general"],
["multilateral","багатосторонній","adjective","B2","general"],
["imminent","неминучий (близький)","adjective","B2","general"],
["redundant","зайвий","adjective","B2","work"],
["contingent","залежний від умов","adjective","B2","general"],
["cumulative","кумулятивний","adjective","B2","general"],
["aggregate","сукупний","adjective","B2","general"],
["overarching","всеохопний","adjective","B2","general"],
["underlying","основний","adjective","B2","general"],
["reciprocal","взаємозалежний","adjective","B2","general"],
["concurrent","одночасний","adjective","B2","general"],
["preliminary","попередній","adjective","B2","general"],
["integral","невід'ємний","adjective","B2","general"],
["marginal","незначний","adjective","B2","general"],
["lucrative","вигідний","adjective","B2","business"],
["viable","життєздатний","adjective","B2","business"],
["plausible","правдоподібний","adjective","B2","general"],
["feasible","здійсненний","adjective","B2","general"],
["inevitable","неминучий","adjective","B2","general"],
["unprecedented","безпрецедентний","adjective","B2","general"],
["groundbreaking","новаторський","adjective","B2","general"],
["cutting-edge","передовий","adjective","B2","technology"],
["obsolete","застарілий","adjective","B2","technology"],
// B2 adverbs additional
["systematically","систематично","adverb","B2","general"],
["comprehensively","всебічно","adverb","B2","general"],
["retrospectively","ретроспективно","adverb","B2","general"],
["prospectively","перспективно","adverb","B2","general"],
["exclusively","виключно","adverb","B2","general"],
["precisely","точно","adverb","B2","general"],
["fundamentally","принципово","adverb","B2","general"],
["inherently","за своєю суттю","adverb","B2","general"],
["inevitably","з неминучістю","adverb","B2","general"],
["relatively","відносно","adverb","B2","general"],
["substantially","суттєво","adverb","B2","general"],
["extensively","в широких масштабах","adverb","B2","general"],
];

// Dedup & validate
const seen = new Set();
const validPos = new Set(["verb","noun","adjective","adverb","number","conjunction","preposition","phrase"]);
const validLevels = new Set(["A2","B1","B2"]);

const newWords3 = [];
let dupExist=0, dupInternal=0, bad=0;
for (const [en,ua,pos,level,topic] of RAW3) {
  const key = en.toLowerCase();
  if (existSet.has(key))       { dupExist++; continue; }
  if (seen.has(key))           { dupInternal++; continue; }
  if (!validPos.has(pos) || !validLevels.has(level) || !en || !ua || !topic) { bad++; continue; }
  seen.add(key);
  newWords3.push({en,ua,pos,level,topic});
}
console.log(`Candidates: ${RAW3.length}, skip_exist: ${dupExist}, skip_dup: ${dupInternal}, bad: ${bad}`);
console.log(`New batch3: ${newWords3.length}`);
const byL={}, byP={};
newWords3.forEach(w=>{byL[w.level]=(byL[w.level]||0)+1; byP[w.pos]=(byP[w.pos]||0)+1;});
console.log('By level:', byL); console.log('By pos:', byP);
fs.writeFileSync('./new_batch3.json', JSON.stringify(newWords3, null, 2));
console.log('Wrote new_batch3.json');
