'use strict';
const fs = require('fs');

const existing = JSON.parse(fs.readFileSync('./words.json', 'utf8'));
const existSet = new Set(existing.map(w => w.en.toLowerCase()));

// ── ALL CANDIDATE WORDS ──────────────────────────────────────────────────────
// Each entry: [en, ua, pos, level, topic]
// Generated in thematic groups; duplicates vs existing are removed below.
const RAW = [

// ═══════════════ A2 NOUNS ═══════════════
// body
["shoulder","плече","noun","A2","body"],
["elbow","лікоть","noun","A2","body"],
["knee","коліно","noun","A2","body"],
["ankle","щиколотка","noun","A2","body"],
["thumb","великий палець","noun","A2","body"],
["toe","палець ноги","noun","A2","body"],
["chin","підборіддя","noun","A2","body"],
["cheek","щока","noun","A2","body"],
["forehead","лоб","noun","A2","body"],
["wrist","зап'ясток","noun","A2","body"],
["nail","ніготь","noun","A2","body"],
["lip","губа","noun","A2","body"],
["tooth","зуб","noun","A2","body"],
["throat","горло","noun","A2","body"],
["chest","груди","noun","A2","body"],
["stomach","живіт","noun","A2","body"],
["heel","п'ята","noun","A2","body"],
["palm","долоня","noun","A2","body"],
["bone","кістка","noun","A2","body"],
["skin","шкіра","noun","A2","body"],
["blood","кров","noun","A2","body"],
["muscle","м'яз","noun","A2","body"],
// clothing
["pants","штани","noun","A2","clothing"],
["boot","чобіт","noun","A2","clothing"],
["sock","шкарпетка","noun","A2","clothing"],
["scarf","шарф","noun","A2","clothing"],
["glove","рукавичка","noun","A2","clothing"],
["suit","костюм","noun","A2","clothing"],
["belt","пояс","noun","A2","clothing"],
["pocket","кишеня","noun","A2","clothing"],
["sleeve","рукав","noun","A2","clothing"],
["collar","комір","noun","A2","clothing"],
["zip","блискавка","noun","A2","clothing"],
["cap","кепка","noun","A2","clothing"],
["swimsuit","купальник","noun","A2","clothing"],
["uniform","форма","noun","A2","clothing"],
// food & drink
["pepper","перець","noun","A2","food"],
["oil","олія","noun","A2","food"],
["lemon","лимон","noun","A2","food"],
["grape","виноград","noun","A2","food"],
["strawberry","полуниця","noun","A2","food"],
["carrot","морква","noun","A2","food"],
["mushroom","гриб","noun","A2","food"],
["pear","груша","noun","A2","food"],
["cherry","вишня","noun","A2","food"],
["plum","слива","noun","A2","food"],
["watermelon","кавун","noun","A2","food"],
["honey","мед","noun","A2","food"],
["jam","варення","noun","A2","food"],
["flour","борошно","noun","A2","food"],
["cream","вершки","noun","A2","food"],
["yogurt","йогурт","noun","A2","food"],
["noodle","локшина","noun","A2","food"],
["snack","закуска","noun","A2","food"],
["dessert","десерт","noun","A2","food"],
["meal","страва","noun","A2","food"],
["dish","блюдо","noun","A2","food"],
["sausage","ковбаса","noun","A2","food"],
["ham","шинка","noun","A2","food"],
["bacon","бекон","noun","A2","food"],
["bean","квасоля","noun","A2","food"],
["pea","горошок","noun","A2","food"],
["corn","кукурудза","noun","A2","food"],
["cabbage","капуста","noun","A2","food"],
["cucumber","огірок","noun","A2","food"],
["garlic","часник","noun","A2","food"],
["onion","цибуля","noun","A2","food"],
["pumpkin","гарбуз","noun","A2","food"],
["peach","персик","noun","A2","food"],
["melon","диня","noun","A2","food"],
// home & furniture
["ceiling","стеля","noun","A2","home"],
["carpet","килим","noun","A2","home"],
["shelf","полиця","noun","A2","home"],
["curtain","штора","noun","A2","home"],
["tap","кран","noun","A2","home"],
["shower","душ","noun","A2","home"],
["toilet","туалет","noun","A2","home"],
["lamp","лампа","noun","A2","home"],
["mirror","дзеркало","noun","A2","home"],
["sofa","диван","noun","A2","home"],
["desk","письмовий стіл","noun","A2","home"],
["pot","каструля","noun","A2","home"],
["pan","сковорода","noun","A2","home"],
["oven","духовка","noun","A2","home"],
["microwave","мікрохвильовка","noun","A2","home"],
["soap","мило","noun","A2","home"],
["towel","рушник","noun","A2","home"],
["lock","замок","noun","A2","home"],
["lift","ліфт","noun","A2","home"],
["iron","праска","noun","A2","home"],
["vacuum cleaner","пилосос","noun","A2","home"],
["washing machine","пральна машина","noun","A2","home"],
["plug","штепсель","noun","A2","home"],
["switch","вимикач","noun","A2","home"],
["bin","смітник","noun","A2","home"],
["drawer","шухляда","noun","A2","home"],
["pillow","подушка","noun","A2","home"],
["blanket","ковдра","noun","A2","home"],
["sheet","простирадло","noun","A2","home"],
["armchair","крісло","noun","A2","home"],
["wardrobe","шафа","noun","A2","home"],
// places
["library","бібліотека","noun","A2","places"],
["cinema","кінотеатр","noun","A2","places"],
["museum","музей","noun","A2","places"],
["church","церква","noun","A2","places"],
["bridge","міст","noun","A2","places"],
["building","будівля","noun","A2","places"],
["gym","спортзал","noun","A2","sport"],
["supermarket","супермаркет","noun","A2","shopping"],
["post office","пошта","noun","A2","places"],
["stadium","стадіон","noun","A2","sport"],
["flat","квартира","noun","A2","home"],
["fountain","фонтан","noun","A2","places"],
["square","площа","noun","A2","places"],
["port","порт","noun","A2","places"],
// nature & weather
["lake","озеро","noun","A2","nature"],
["island","острів","noun","A2","nature"],
["star","зірка","noun","A2","nature"],
["moon","місяць","noun","A2","nature"],
["earth","земля","noun","A2","nature"],
["sand","пісок","noun","A2","nature"],
["fog","туман","noun","A2","weather"],
["ice","лід","noun","A2","weather"],
["storm","буря","noun","A2","weather"],
["rainbow","веселка","noun","A2","weather"],
["wave","хвиля","noun","A2","nature"],
["cave","печера","noun","A2","nature"],
["valley","долина","noun","A2","nature"],
["hill","пагорб","noun","A2","nature"],
["cliff","скеля","noun","A2","nature"],
// animals
["duck","качка","noun","A2","animals"],
["sheep","вівця","noun","A2","animals"],
["rabbit","кролик","noun","A2","animals"],
["bear","ведмідь","noun","A2","animals"],
["lion","лев","noun","A2","animals"],
["tiger","тигр","noun","A2","animals"],
["elephant","слон","noun","A2","animals"],
["monkey","мавпа","noun","A2","animals"],
["cow","корова","noun","A2","animals"],
["pig","свиня","noun","A2","animals"],
["horse","кінь","noun","A2","animals"],
["wolf","вовк","noun","A2","animals"],
["fox","лисиця","noun","A2","animals"],
["snake","змія","noun","A2","animals"],
["butterfly","метелик","noun","A2","animals"],
["bee","бджола","noun","A2","animals"],
["frog","жаба","noun","A2","animals"],
["deer","олень","noun","A2","animals"],
["eagle","орел","noun","A2","animals"],
["parrot","папуга","noun","A2","animals"],
// transport
["bike","велосипед","noun","A2","transport"],
["truck","вантажівка","noun","A2","transport"],
["ferry","поромна переправа","noun","A2","transport"],
["helicopter","гелікоптер","noun","A2","transport"],
["subway","метро","noun","A2","transport"],
// general objects
["umbrella","парасолька","noun","A2","general"],
["wallet","гаманець","noun","A2","general"],
["ring","каблучка","noun","A2","general"],
["necklace","намисто","noun","A2","general"],
["magazine","журнал","noun","A2","general"],
["stamp","поштова марка","noun","A2","general"],
["envelope","конверт","noun","A2","general"],
["alarm","будильник","noun","A2","general"],
["shape","форма","noun","A2","general"],
["photo","фотографія","noun","A2","general"],
["picture","малюнок","noun","A2","general"],
["coin","монета","noun","A2","money"],
["receipt","чек","noun","A2","shopping"],
["address","адреса","noun","A2","communication"],
["cable","кабель","noun","A2","technology"],
["battery","батарея","noun","A2","technology"],
// school / language
["word","слово","noun","A2","school"],
["sentence","речення","noun","A2","school"],
["story","розповідь","noun","A2","general"],
["paragraph","абзац","noun","A2","school"],
["subject","предмет","noun","A2","school"],
["lesson","урок","noun","A2","school"],
["exam","іспит","noun","A2","school"],
["grade","оцінка","noun","A2","school"],
["dictionary","словник","noun","A2","school"],
["textbook","підручник","noun","A2","school"],
["blackboard","дошка","noun","A2","school"],
["pencil","олівець","noun","A2","school"],
["ruler","лінійка","noun","A2","school"],
["scissors","ножиці","noun","A2","school"],
["glue","клей","noun","A2","school"],
// hobby / sport
["game","гра","noun","A2","hobby"],
["song","пісня","noun","A2","hobby"],
["music","музика","noun","A2","hobby"],
["team","команда","noun","A2","sport"],
["ball","м'яч","noun","A2","sport"],
["sport","спорт","noun","A2","sport"],
["player","гравець","noun","A2","sport"],
["match","матч","noun","A2","sport"],
["score","рахунок","noun","A2","sport"],
["goal","гол","noun","A2","sport"],
["race","перегони","noun","A2","sport"],
["club","клуб","noun","A2","hobby"],
["instrument","інструмент","noun","A2","hobby"],
// family / people
["baby","немовля","noun","A2","family"],
["neighbor","сусід","noun","A2","daily life"],
["guest","гість","noun","A2","daily life"],
["crowd","натовп","noun","A2","general"],

// ═══════════════ A2 VERBS ═══════════════
["jump","стрибати","verb","A2","daily life"],
["run","бігти","verb","A2","daily life"],
["sit","сидіти","verb","A2","daily life"],
["stand","стояти","verb","A2","daily life"],
["fall","падати","verb","A2","daily life"],
["carry","нести","verb","A2","daily life"],
["hold","тримати","verb","A2","daily life"],
["bring","приносити","verb","A2","daily life"],
["move","рухатися","verb","A2","daily life"],
["turn","повертати","verb","A2","daily life"],
["push","штовхати","verb","A2","daily life"],
["pull","тягнути","verb","A2","daily life"],
["drop","кидати","verb","A2","daily life"],
["pack","пакувати","verb","A2","travel"],
["meet","зустрічати","verb","A2","daily life"],
["visit","відвідувати","verb","A2","daily life"],
["play","грати","verb","A2","hobby"],
["sing","співати","verb","A2","hobby"],
["dance","танцювати","verb","A2","hobby"],
["paint","фарбувати","verb","A2","hobby"],
["swim","плавати","verb","A2","sport"],
["drive","водити","verb","A2","transport"],
["fly","літати","verb","A2","transport"],
["climb","лазити","verb","A2","daily life"],
["smile","посміхатися","verb","A2","emotions"],
["laugh","сміятися","verb","A2","emotions"],
["cry","плакати","verb","A2","emotions"],
["miss","сумувати за","verb","A2","emotions"],
["wear","носити (одяг)","verb","A2","clothing"],
["cut","різати","verb","A2","daily life"],
["break","ламати","verb","A2","daily life"],
["fix","лагодити","verb","A2","daily life"],
["build","будувати","verb","A2","daily life"],
["grow","рости","verb","A2","nature"],
["plant","садити","verb","A2","nature"],
["hang","вішати","verb","A2","daily life"],
["heat","нагрівати","verb","A2","daily life"],
["cool","охолоджувати","verb","A2","daily life"],
["pour","наливати","verb","A2","food"],
["mix","змішувати","verb","A2","food"],
["boil","кипіти","verb","A2","food"],
["fry","смажити","verb","A2","food"],
["bake","пекти","verb","A2","food"],
["save","зберігати","verb","A2","general"],
["lose","втрачати","verb","A2","general"],
["win","вигравати","verb","A2","sport"],
["score","забивати гол","verb","A2","sport"],
["practice","практикуватися","verb","A2","general"],
["hurry","поспішати","verb","A2","daily life"],
["relax","відпочивати","verb","A2","daily life"],
["return","повертатися","verb","A2","daily life"],
["arrive","прибувати","verb","A2","travel"],
["enter","входити","verb","A2","daily life"],
["exit","виходити","verb","A2","daily life"],
["lock","замикати","verb","A2","home"],
["knock","стукати","verb","A2","daily life"],
["ring","дзвонити","verb","A2","communication"],
["point","вказувати","verb","A2","general"],
["touch","торкатися","verb","A2","general"],
["catch","ловити","verb","A2","daily life"],
["throw","кидати","verb","A2","sport"],
["lift","піднімати","verb","A2","daily life"],
["bite","кусати","verb","A2","daily life"],
["kick","вдаряти ногою","verb","A2","sport"],
["rent","орендувати","verb","A2","home"],
["borrow","позичати","verb","A2","general"],
["lend","давати в позику","verb","A2","general"],
["share","ділитися","verb","A2","general"],
["choose","вибирати","verb","A2","general"],
["collect","збирати","verb","A2","hobby"],
["earn","заробляти","verb","A2","money"],
["spend","витрачати","verb","A2","money"],
["invite","запрошувати","verb","A2","daily life"],
["celebrate","святкувати","verb","A2","daily life"],
["surprise","дивувати","verb","A2","emotions"],
["promise","обіцяти","verb","A2","general"],
["suggest","пропонувати","verb","A2","general"],
["agree","погоджуватися","verb","A2","general"],
["refuse","відмовлятися","verb","A2","general"],
["follow","слідувати","verb","A2","general"],
["check","перевіряти","verb","A2","general"],
["pack","збиратися","verb","A2","travel"],
["ride","їздити верхи","verb","A2","transport"],

// ═══════════════ A2 ADJECTIVES ═══════════════
["tall","високий","adjective","A2","general"],
["thin","тонкий","adjective","A2","general"],
["fat","товстий","adjective","A2","general"],
["cool","прохолодний","adjective","A2","general"],
["sour","кислий","adjective","A2","food"],
["salty","солоний","adjective","A2","food"],
["spicy","гострий","adjective","A2","food"],
["delicious","смачний","adjective","A2","food"],
["hungry","голодний","adjective","A2","health"],
["thirsty","спраглий","adjective","A2","health"],
["loud","гучний","adjective","A2","general"],
["closed","закритий","adjective","A2","general"],
["same","однаковий","adjective","A2","general"],
["sunny","сонячний","adjective","A2","weather"],
["cloudy","хмарний","adjective","A2","weather"],
["rainy","дощовий","adjective","A2","weather"],
["windy","вітряний","adjective","A2","weather"],
["snowy","снігований","adjective","A2","weather"],
["foggy","туманний","adjective","A2","weather"],
["wet","мокрий","adjective","A2","general"],
["wide","широкий","adjective","A2","general"],
["narrow","вузький","adjective","A2","general"],
["deep","глибокий","adjective","A2","general"],
["shallow","мілкий","adjective","A2","general"],
["round","круглий","adjective","A2","general"],
["straight","прямий","adjective","A2","general"],
["bright","яскравий","adjective","A2","general"],
["boring","нудний","adjective","A2","emotions"],
["funny","смішний","adjective","A2","emotions"],
["cute","милий","adjective","A2","general"],
["ugly","потворний","adjective","A2","general"],
["strange","дивний","adjective","A2","general"],
["perfect","ідеальний","adjective","A2","general"],
["terrible","жахливий","adjective","A2","general"],
["wonderful","чудовий","adjective","A2","general"],
["amazing","дивовижний","adjective","A2","general"],
["delicate","тендітний","adjective","A2","general"],
["sharp","гострий (про ніж)","adjective","A2","general"],
["flat","плаский","adjective","A2","general"],
["frozen","заморожений","adjective","A2","food"],
["fresh","свіжий","adjective","A2","food"],
["raw","сирий","adjective","A2","food"],
["cooked","приготований","adjective","A2","food"],
["ripe","стиглий","adjective","A2","food"],
["broken","зламаний","adjective","A2","general"],
["lost","загублений","adjective","A2","general"],
["early","ранній","adjective","A2","time"],
["late","пізній","adjective","A2","time"],
["alone","самотній","adjective","A2","general"],
["clever","розумний","adjective","A2","general"],
["lazy","ледачий","adjective","A2","general"],
["polite","ввічливий","adjective","A2","general"],
["rude","грубий","adjective","A2","general"],
["shy","сором'язливий","adjective","A2","general"],
["brave","хоробрий","adjective","A2","general"],
// A2 ADVERBS
["slowly","повільно","adverb","A2","general"],
["quickly","швидко","adverb","A2","general"],
["quietly","тихо","adverb","A2","general"],
["loudly","голосно","adverb","A2","general"],
["carefully","обережно","adverb","A2","general"],
["suddenly","раптово","adverb","A2","general"],
["together","разом","adverb","A2","general"],
["outside","надворі","adverb","A2","general"],
["inside","всередині","adverb","A2","general"],
["upstairs","нагорі","adverb","A2","home"],
["downstairs","внизу","adverb","A2","home"],
["enough","достатньо","adverb","A2","general"],
["away","далеко","adverb","A2","general"],
["ahead","вперед","adverb","A2","general"],
["instead","замість","adverb","A2","general"],

// ═══════════════ B1 NOUNS ═══════════════
// emotions / personality
["emotion","емоція","noun","B1","emotions"],
["mood","настрій","noun","B1","emotions"],
["attitude","ставлення","noun","B1","emotions"],
["confidence","впевненість","noun","B1","emotions"],
["courage","мужність","noun","B1","emotions"],
["patience","терпіння","noun","B1","emotions"],
["jealousy","ревнощі","noun","B1","emotions"],
["guilt","провина","noun","B1","emotions"],
["shame","сором","noun","B1","emotions"],
["pride","гордість","noun","B1","emotions"],
["disappointment","розчарування","noun","B1","emotions"],
["excitement","хвилювання","noun","B1","emotions"],
["satisfaction","задоволення","noun","B1","emotions"],
["loneliness","самотність","noun","B1","emotions"],
["jealousy","ревність","noun","B1","emotions"],
// work / business
["colleague","колега","noun","B1","work"],
["employee","працівник","noun","B1","work"],
["employer","роботодавець","noun","B1","work"],
["profession","професія","noun","B1","work"],
["career","кар'єра","noun","B1","work"],
["salary","зарплата","noun","B1","work"],
["contract","контракт","noun","B1","work"],
["deadline","кінцевий термін","noun","B1","work"],
["meeting","зустріч","noun","B1","work"],
["project","проект","noun","B1","work"],
["budget","бюджет","noun","B1","money"],
["profit","прибуток","noun","B1","money"],
["loss","збиток","noun","B1","money"],
["investment","інвестиція","noun","B1","money"],
["tax","податок","noun","B1","money"],
["loan","позика","noun","B1","money"],
["debt","борг","noun","B1","money"],
["account","рахунок","noun","B1","money"],
["payment","платіж","noun","B1","money"],
["discount","знижка","noun","B1","shopping"],
["price","ціна","noun","B1","shopping"],
["advertisement","реклама","noun","B1","business"],
["brand","бренд","noun","B1","business"],
["product","продукт","noun","B1","business"],
["service","послуга","noun","B1","business"],
["customer","клієнт","noun","B1","business"],
["market","ринок","noun","B1","business"],
["competition","конкуренція","noun","B1","business"],
["company","компанія","noun","B1","business"],
["industry","галузь","noun","B1","business"],
["factory","завод","noun","B1","work"],
// health
["disease","хвороба","noun","B1","health"],
["treatment","лікування","noun","B1","health"],
["surgery","операція","noun","B1","health"],
["symptom","симптом","noun","B1","health"],
["diagnosis","діагноз","noun","B1","health"],
["prescription","рецепт","noun","B1","health"],
["vaccine","вакцина","noun","B1","health"],
["injury","травма","noun","B1","health"],
["allergy","алергія","noun","B1","health"],
["diet","дієта","noun","B1","health"],
["vitamin","вітамін","noun","B1","health"],
["medicine","ліки","noun","B1","health"],
["pharmacy","аптека","noun","B1","health"],
["ambulance","швидка допомога","noun","B1","health"],
["dentist","стоматолог","noun","B1","health"],
["nurse","медсестра","noun","B1","health"],
["appointment","прийом","noun","B1","health"],
// technology
["software","програмне забезпечення","noun","B1","technology"],
["hardware","обладнання","noun","B1","technology"],
["application","додаток","noun","B1","technology"],
["file","файл","noun","B1","technology"],
["folder","папка","noun","B1","technology"],
["document","документ","noun","B1","technology"],
["database","база даних","noun","B1","technology"],
["virus","вірус","noun","B1","technology"],
["update","оновлення","noun","B1","technology"],
["error","помилка","noun","B1","technology"],
["search","пошук","noun","B1","technology"],
["data","дані","noun","B1","technology"],
["network","мережа","noun","B1","technology"],
["connection","з'єднання","noun","B1","technology"],
["server","сервер","noun","B1","technology"],
["cloud","хмара","noun","B1","technology"],
["smartphone","смартфон","noun","B1","technology"],
["tablet","планшет","noun","B1","technology"],
["laptop","ноутбук","noun","B1","technology"],
["printer","принтер","noun","B1","technology"],
// education
["knowledge","знання","noun","B1","school"],
["skill","навичка","noun","B1","school"],
["ability","здатність","noun","B1","school"],
["experience","досвід","noun","B1","school"],
["research","дослідження","noun","B1","school"],
["experiment","експеримент","noun","B1","school"],
["theory","теорія","noun","B1","school"],
["method","метод","noun","B1","school"],
["result","результат","noun","B1","school"],
["problem","проблема","noun","B1","general"],
["solution","розв'язання","noun","B1","general"],
["goal","мета","noun","B1","general"],
["progress","прогрес","noun","B1","general"],
["development","розвиток","noun","B1","general"],
["improvement","поліпшення","noun","B1","general"],
["challenge","виклик","noun","B1","general"],
["mistake","помилка","noun","B1","general"],
// communication
["opinion","думка","noun","B1","communication"],
["argument","аргумент","noun","B1","communication"],
["debate","дискусія","noun","B1","communication"],
["conversation","розмова","noun","B1","communication"],
["speech","промова","noun","B1","communication"],
["discussion","обговорення","noun","B1","communication"],
["interview","інтерв'ю","noun","B1","communication"],
["survey","опитування","noun","B1","communication"],
["report","звіт","noun","B1","work"],
["presentation","презентація","noun","B1","work"],
// culture / society
["culture","культура","noun","B1","general"],
["tradition","традиція","noun","B1","general"],
["religion","релігія","noun","B1","general"],
["language","мова","noun","B1","general"],
["history","історія","noun","B1","general"],
["politics","політика","noun","B1","general"],
["government","уряд","noun","B1","general"],
["law","закон","noun","B1","general"],
["rule","правило","noun","B1","general"],
["right","право","noun","B1","general"],
["freedom","свобода","noun","B1","general"],
["society","суспільство","noun","B1","general"],
["community","спільнота","noun","B1","general"],
["citizen","громадянин","noun","B1","general"],
["population","населення","noun","B1","general"],
["generation","покоління","noun","B1","general"],
["vote","голос","noun","B1","general"],
["election","вибори","noun","B1","general"],
// travel / places
["tour","екскурсія","noun","B1","travel"],
["destination","пункт призначення","noun","B1","travel"],
["souvenir","сувенір","noun","B1","travel"],
["luggage","багаж","noun","B1","travel"],
["passport","паспорт","noun","B1","travel"],
["visa","віза","noun","B1","travel"],
["accommodation","проживання","noun","B1","travel"],
["reservation","бронювання","noun","B1","travel"],
["schedule","розклад","noun","B1","travel"],
["currency","валюта","noun","B1","money"],
["border","кордон","noun","B1","travel"],
["customs","митниця","noun","B1","travel"],
["guide","гід","noun","B1","travel"],
["attraction","визначна пам'ятка","noun","B1","travel"],
["landscape","краєвид","noun","B1","nature"],
["coast","узбережжя","noun","B1","nature"],
["harbour","гавань","noun","B1","nature"],
// nature / environment
["environment","навколишнє середовище","noun","B1","nature"],
["pollution","забруднення","noun","B1","nature"],
["climate","клімат","noun","B1","nature"],
["earthquake","землетрус","noun","B1","nature"],
["flood","повінь","noun","B1","nature"],
["fire","пожежа","noun","B1","nature"],
["drought","посуха","noun","B1","nature"],
["temperature","температура","noun","B1","weather"],
["humidity","вологість","noun","B1","weather"],
["season","сезон","noun","B1","weather"],
// food (B1)
["nutrition","харчування","noun","B1","food"],
["calorie","калорія","noun","B1","food"],
["ingredient","інгредієнт","noun","B1","food"],
["recipe","рецепт","noun","B1","food"],
["vegetarian","вегетаріанець","noun","B1","food"],
["portion","порція","noun","B1","food"],
["flavour","смак","noun","B1","food"],
["appetite","апетит","noun","B1","food"],
// art / entertainment
["exhibition","виставка","noun","B1","hobby"],
["gallery","галерея","noun","B1","hobby"],
["concert","концерт","noun","B1","hobby"],
["performance","вистава","noun","B1","hobby"],
["novel","роман","noun","B1","hobby"],
["poet","поет","noun","B1","hobby"],
["fiction","художня литература","noun","B1","hobby"],
["documentary","документальний фільм","noun","B1","hobby"],
["cartoon","мультфільм","noun","B1","hobby"],
["theatre","театр","noun","B1","hobby"],
["audience","глядачі","noun","B1","hobby"],
["character","персонаж","noun","B1","hobby"],
["plot","сюжет","noun","B1","hobby"],
["scene","сцена","noun","B1","hobby"],

// ═══════════════ B1 VERBS ═══════════════
["achieve","досягати","verb","B1","general"],
["improve","покращувати","verb","B1","general"],
["develop","розвивати","verb","B1","general"],
["increase","збільшувати","verb","B1","general"],
["decrease","зменшувати","verb","B1","general"],
["reduce","скорочувати","verb","B1","general"],
["raise","підвищувати","verb","B1","general"],
["lower","знижувати","verb","B1","general"],
["compare","порівнювати","verb","B1","general"],
["consider","розглядати","verb","B1","general"],
["depend","залежати","verb","B1","general"],
["expect","очікувати","verb","B1","general"],
["prepare","готуватися","verb","B1","general"],
["provide","надавати","verb","B1","general"],
["require","вимагати","verb","B1","general"],
["support","підтримувати","verb","B1","general"],
["prevent","запобігати","verb","B1","health"],
["recover","одужувати","verb","B1","health"],
["examine","обстежувати","verb","B1","health"],
["treat","лікувати","verb","B1","health"],
["recommend","рекомендувати","verb","B1","general"],
["contact","зв'язуватися","verb","B1","communication"],
["communicate","спілкуватися","verb","B1","communication"],
["express","висловлювати","verb","B1","communication"],
["translate","перекладати","verb","B1","school"],
["present","представляти","verb","B1","work"],
["organize","організовувати","verb","B1","work"],
["manage","керувати","verb","B1","work"],
["lead","очолювати","verb","B1","work"],
["hire","наймати","verb","B1","work"],
["fire","звільняти","verb","B1","work"],
["apply","подавати заяву","verb","B1","work"],
["attend","відвідувати","verb","B1","general"],
["create","створювати","verb","B1","general"],
["design","проектувати","verb","B1","general"],
["analyse","аналізувати","verb","B1","general"],
["measure","вимірювати","verb","B1","general"],
["test","тестувати","verb","B1","general"],
["search","шукати","verb","B1","general"],
["discover","відкривати","verb","B1","general"],
["explore","досліджувати","verb","B1","general"],
["investigate","розслідувати","verb","B1","general"],
["solve","вирішувати","verb","B1","general"],
["plan","планувати","verb","B1","general"],
["schedule","планувати розклад","verb","B1","work"],
["collaborate","співпрацювати","verb","B1","work"],
["negotiate","переговорювати","verb","B1","work"],
["approve","схвалювати","verb","B1","work"],
["reject","відхиляти","verb","B1","general"],
["accept","приймати","verb","B1","general"],
["confirm","підтверджувати","verb","B1","general"],
["cancel","скасовувати","verb","B1","general"],
["borrow","позичати","verb","B1","money"],
["save","економити","verb","B1","money"],
["invest","інвестувати","verb","B1","money"],
["earn","заробляти","verb","B1","money"],
["spend","витрачати","verb","B1","money"],
["charge","стягувати плату","verb","B1","money"],
["afford","мати змогу купити","verb","B1","money"],
["book","бронювати","verb","B1","travel"],
["travel","подорожувати","verb","B1","travel"],
["pack","складати валізу","verb","B1","travel"],
["tour","відвідувати","verb","B1","travel"],
["recycle","переробляти","verb","B1","nature"],
["protect","захищати","verb","B1","general"],
["damage","завдавати шкоди","verb","B1","general"],
["pollute","забруднювати","verb","B1","nature"],
["survive","виживати","verb","B1","general"],
["escape","тікати","verb","B1","general"],
["avoid","уникати","verb","B1","general"],
["risk","ризикувати","verb","B1","general"],
["bother","турбувати","verb","B1","emotions"],
["complain","скаржитися","verb","B1","emotions"],
["trust","довіряти","verb","B1","emotions"],
["doubt","сумніватися","verb","B1","emotions"],
["forgive","прощати","verb","B1","emotions"],
["blame","звинувачувати","verb","B1","emotions"],
["encourage","заохочувати","verb","B1","emotions"],
["inspire","надихати","verb","B1","emotions"],
["convince","переконувати","verb","B1","communication"],
["warn","попереджати","verb","B1","communication"],
["mention","зазначати","verb","B1","communication"],
["notice","помічати","verb","B1","general"],
["publish","публікувати","verb","B1","general"],
["edit","редагувати","verb","B1","general"],
["review","рецензувати","verb","B1","general"],
["upload","завантажувати","verb","B1","technology"],
["download","скачувати","verb","B1","technology"],
["install","встановлювати","verb","B1","technology"],
["connect","підключати","verb","B1","technology"],
["update","оновлювати","verb","B1","technology"],
["delete","видаляти","verb","B1","technology"],
["access","отримувати доступ","verb","B1","technology"],
["secure","захищати","verb","B1","technology"],
["share","ділитися","verb","B1","technology"],
["stream","стримити","verb","B1","technology"],

// ═══════════════ B1 ADJECTIVES ═══════════════
["responsible","відповідальний","adjective","B1","general"],
["reasonable","розумний","adjective","B1","general"],
["reliable","надійний","adjective","B1","general"],
["efficient","ефективний","adjective","B1","work"],
["effective","дієвий","adjective","B1","work"],
["flexible","гнучкий","adjective","B1","work"],
["creative","творчий","adjective","B1","work"],
["professional","професійний","adjective","B1","work"],
["experienced","досвідчений","adjective","B1","work"],
["qualified","кваліфікований","adjective","B1","work"],
["motivated","мотивований","adjective","B1","work"],
["talented","талановитий","adjective","B1","general"],
["intelligent","інтелектуальний","adjective","B1","general"],
["curious","допитливий","adjective","B1","general"],
["ambitious","амбіційний","adjective","B1","general"],
["determined","рішучий","adjective","B1","general"],
["generous","щедрий","adjective","B1","general"],
["honest","чесний","adjective","B1","general"],
["loyal","відданий","adjective","B1","general"],
["cheerful","радісний","adjective","B1","emotions"],
["nervous","нервовий","adjective","B1","emotions"],
["anxious","стривожений","adjective","B1","emotions"],
["stressed","у стресі","adjective","B1","emotions"],
["depressed","пригнічений","adjective","B1","emotions"],
["confused","розгублений","adjective","B1","emotions"],
["embarrassed","збентежений","adjective","B1","emotions"],
["proud","гордий","adjective","B1","emotions"],
["jealous","ревнивий","adjective","B1","emotions"],
["bored","нудьгуючий","adjective","B1","emotions"],
["curious","цікавий","adjective","B1","general"],
["comfortable","комфортний","adjective","B1","home"],
["convenient","зручний","adjective","B1","general"],
["available","доступний","adjective","B1","general"],
["popular","популярний","adjective","B1","general"],
["useful","корисний","adjective","B1","general"],
["harmful","шкідливий","adjective","B1","health"],
["healthy","здоровий","adjective","B1","health"],
["common","поширений","adjective","B1","general"],
["traditional","традиційний","adjective","B1","general"],
["modern","сучасний","adjective","B1","general"],
["local","місцевий","adjective","B1","general"],
["global","глобальний","adjective","B1","general"],
["natural","природний","adjective","B1","nature"],
["organic","органічний","adjective","B1","food"],
["expensive","дорогий","adjective","B1","shopping"],
["affordable","доступний за ціною","adjective","B1","shopping"],
["necessary","необхідний","adjective","B1","general"],
["optional","необов'язковий","adjective","B1","general"],
["urgent","терміновий","adjective","B1","general"],
["serious","серйозний","adjective","B1","general"],
["formal","офіційний","adjective","B1","work"],
["informal","неофіційний","adjective","B1","general"],
["significant","значний","adjective","B1","general"],
["surprising","дивовижний","adjective","B1","general"],

// ═══════════════ B1 ADVERBS ═══════════════
["mainly","переважно","adverb","B1","general"],
["generally","загалом","adverb","B1","general"],
["particularly","особливо","adverb","B1","general"],
["recently","нещодавно","adverb","B1","time"],
["immediately","одразу","adverb","B1","time"],
["eventually","зрештою","adverb","B1","time"],
["gradually","поступово","adverb","B1","general"],
["constantly","постійно","adverb","B1","general"],
["rarely","рідко","adverb","B1","time"],
["frequently","часто","adverb","B1","time"],
["briefly","коротко","adverb","B1","general"],
["exactly","саме","adverb","B1","general"],
["mostly","здебільшого","adverb","B1","general"],
["completely","повністю","adverb","B1","general"],
["mainly","головним чином","adverb","B1","general"],
["directly","безпосередньо","adverb","B1","general"],
["properly","правильно","adverb","B1","general"],
["clearly","чітко","adverb","B1","general"],
["mostly","в основному","adverb","B1","general"],
["officially","офіційно","adverb","B1","general"],
["initially","спочатку","adverb","B1","time"],
["meanwhile","тим часом","adverb","B1","time"],
["otherwise","інакше","adverb","B1","general"],

// ═══════════════ B2 NOUNS ═══════════════
// abstract / academic
["concept","концепція","noun","B2","general"],
["principle","принцип","noun","B2","general"],
["phenomenon","явище","noun","B2","general"],
["perspective","точка зору","noun","B2","general"],
["aspect","аспект","noun","B2","general"],
["factor","фактор","noun","B2","general"],
["element","елемент","noun","B2","general"],
["structure","структура","noun","B2","general"],
["framework","рамки","noun","B2","general"],
["mechanism","механізм","noun","B2","general"],
["process","процес","noun","B2","general"],
["procedure","процедура","noun","B2","general"],
["strategy","стратегія","noun","B2","general"],
["approach","підхід","noun","B2","general"],
["outcome","результат","noun","B2","general"],
["impact","вплив","noun","B2","general"],
["effect","ефект","noun","B2","general"],
["consequence","наслідок","noun","B2","general"],
["implication","наслідок","noun","B2","general"],
["assumption","припущення","noun","B2","general"],
["hypothesis","гіпотеза","noun","B2","school"],
["evidence","докази","noun","B2","general"],
["argument","аргумент","noun","B2","general"],
["criteria","критерії","noun","B2","general"],
["objective","мета","noun","B2","work"],
["priority","пріоритет","noun","B2","work"],
["initiative","ініціатива","noun","B2","work"],
["innovation","інновація","noun","B2","business"],
["achievement","досягнення","noun","B2","general"],
["contribution","внесок","noun","B2","general"],
["benefit","перевага","noun","B2","general"],
["advantage","переваги","noun","B2","general"],
["disadvantage","недолік","noun","B2","general"],
["obstacle","перешкода","noun","B2","general"],
["barrier","бар'єр","noun","B2","general"],
["opportunity","можливість","noun","B2","general"],
["threat","загроза","noun","B2","general"],
["risk","ризик","noun","B2","general"],
["conflict","конфлікт","noun","B2","general"],
["crisis","криза","noun","B2","general"],
["recession","рецесія","noun","B2","money"],
["inflation","інфляція","noun","B2","money"],
["revenue","виручка","noun","B2","business"],
["expenditure","витрати","noun","B2","money"],
["funding","фінансування","noun","B2","money"],
["grant","грант","noun","B2","money"],
["stakeholder","зацікавлена сторона","noun","B2","business"],
["shareholder","акціонер","noun","B2","business"],
["entrepreneur","підприємець","noun","B2","business"],
["executive","керівник","noun","B2","business"],
["consultant","консультант","noun","B2","work"],
["analyst","аналітик","noun","B2","work"],
["expert","експерт","noun","B2","work"],
["specialist","фахівець","noun","B2","work"],
["candidate","кандидат","noun","B2","work"],
["corporation","корпорація","noun","B2","business"],
["headquarters","штаб-квартира","noun","B2","business"],
["merger","злиття","noun","B2","business"],
["acquisition","поглинання","noun","B2","business"],
["partnership","партнерство","noun","B2","business"],
["regulation","регулювання","noun","B2","general"],
["policy","політика","noun","B2","general"],
["legislation","законодавство","noun","B2","general"],
["constitution","конституція","noun","B2","general"],
["democracy","демократія","noun","B2","general"],
["reform","реформа","noun","B2","general"],
["corruption","корупція","noun","B2","general"],
["infrastructure","інфраструктура","noun","B2","general"],
["sustainability","стійкість","noun","B2","nature"],
["emission","викид","noun","B2","nature"],
["renewable","відновлювана (енергія)","noun","B2","nature"],
["biodiversity","біорізноманіття","noun","B2","nature"],
["ecosystem","екосистема","noun","B2","nature"],
["species","вид","noun","B2","nature"],
["habitat","середовище існування","noun","B2","nature"],
["extinction","вимирання","noun","B2","nature"],
["conservation","охорона природи","noun","B2","nature"],
["welfare","добробут","noun","B2","general"],
["inequality","нерівність","noun","B2","general"],
["discrimination","дискримінація","noun","B2","general"],
["diversity","різноманітність","noun","B2","general"],
["integration","інтеграція","noun","B2","general"],
["phenomenon","феномен","noun","B2","general"],
["perception","сприйняття","noun","B2","general"],
["awareness","обізнаність","noun","B2","general"],
["consciousness","свідомість","noun","B2","general"],
["identity","ідентичність","noun","B2","general"],
["ideology","ідеологія","noun","B2","general"],
["institution","інститут","noun","B2","general"],
["administration","адміністрація","noun","B2","general"],
["bureaucracy","бюрократія","noun","B2","general"],
["diplomat","дипломат","noun","B2","general"],
["sovereignty","суверенітет","noun","B2","general"],
// health B2
["chronic","хронічне захворювання","noun","B2","health"],
["epidemic","епідемія","noun","B2","health"],
["pandemic","пандемія","noun","B2","health"],
["immunity","імунітет","noun","B2","health"],
["metabolism","метаболізм","noun","B2","health"],
["nutrition","живлення","noun","B2","health"],
["obesity","ожиріння","noun","B2","health"],
["addiction","залежність","noun","B2","health"],
["rehabilitation","реабілітація","noun","B2","health"],
["counselling","консультування","noun","B2","health"],
["psychiatry","психіатрія","noun","B2","health"],
["therapy","терапія","noun","B2","health"],
["hormone","гормон","noun","B2","health"],
["gene","ген","noun","B2","health"],
["cell","клітина","noun","B2","health"],
["tissue","тканина","noun","B2","health"],
["organ","орган","noun","B2","health"],
// technology B2
["algorithm","алгоритм","noun","B2","technology"],
["encryption","шифрування","noun","B2","technology"],
["cybersecurity","кібербезпека","noun","B2","technology"],
["artificial intelligence","штучний інтелект","noun","B2","technology"],
["machine learning","машинне навчання","noun","B2","technology"],
["bandwidth","пропускна здатність","noun","B2","technology"],
["interface","інтерфейс","noun","B2","technology"],
["prototype","прототип","noun","B2","technology"],
["deployment","розгортання","noun","B2","technology"],
["infrastructure","ІТ-інфраструктура","noun","B2","technology"],
["automation","автоматизація","noun","B2","technology"],
["platform","платформа","noun","B2","technology"],
["ecosystem","екосистема (технолог.)","noun","B2","technology"],
// science / academic B2
["psychology","психологія","noun","B2","school"],
["sociology","соціологія","noun","B2","school"],
["economics","економіка","noun","B2","school"],
["linguistics","лінгвістика","noun","B2","school"],
["philosophy","філософія","noun","B2","school"],
["ethics","етика","noun","B2","school"],
["methodology","методологія","noun","B2","school"],
["analysis","аналіз","noun","B2","school"],
["synthesis","синтез","noun","B2","school"],
["correlation","кореляція","noun","B2","school"],
["variable","змінна","noun","B2","school"],
["sample","вибірка","noun","B2","school"],
["statistic","статистика","noun","B2","school"],
["survey","дослідження","noun","B2","school"],
["questionnaire","анкета","noun","B2","school"],
["bibliography","бібліографія","noun","B2","school"],
["citation","цитата","noun","B2","school"],
["abstract","анотація","noun","B2","school"],
["thesis","теза","noun","B2","school"],
["peer review","рецензування","noun","B2","school"],
// arts B2
["aesthetic","естетика","noun","B2","hobby"],
["symbolism","символізм","noun","B2","hobby"],
["narrative","розповідь","noun","B2","hobby"],
["genre","жанр","noun","B2","hobby"],
["interpretation","інтерпретація","noun","B2","hobby"],
["critique","критика","noun","B2","hobby"],
["composition","композиція","noun","B2","hobby"],
["medium","засіб (мистецтва)","noun","B2","hobby"],
["installation","інсталяція","noun","B2","hobby"],
// society B2
["phenomenon","суспільне явище","noun","B2","general"],
["stereotype","стереотип","noun","B2","general"],
["bias","упередженість","noun","B2","general"],
["prejudice","забобон","noun","B2","general"],
["tolerance","толерантність","noun","B2","general"],
["empathy","емпатія","noun","B2","general"],
["privilege","привілей","noun","B2","general"],
["marginalization","маргіналізація","noun","B2","general"],
["urbanization","урбанізація","noun","B2","general"],
["globalization","глобалізація","noun","B2","general"],
["migration","міграція","noun","B2","general"],
["refugee","біженець","noun","B2","general"],
// work B2
["mentorship","наставництво","noun","B2","work"],
["productivity","продуктивність","noun","B2","work"],
["efficiency","ефективність","noun","B2","work"],
["transparency","прозорість","noun","B2","work"],
["accountability","відповідальність","noun","B2","work"],
["liability","зобов'язання","noun","B2","work"],
["compliance","відповідність вимогам","noun","B2","work"],
["audit","аудит","noun","B2","work"],
["restructuring","реструктуризація","noun","B2","work"],
["redundancy","скорочення штату","noun","B2","work"],
// extra nouns B2
["momentum","імпульс","noun","B2","general"],
["bandwidth","здатність сприйняття","noun","B2","general"],
["paradigm","парадигма","noun","B2","general"],
["benchmark","еталон","noun","B2","business"],
["portfolio","портфоліо","noun","B2","work"],
["expertise","експертиза","noun","B2","work"],
["legacy","спадщина","noun","B2","general"],
["heritage","культурна спадщина","noun","B2","general"],
["folklore","фольклор","noun","B2","general"],
["mythology","міфологія","noun","B2","general"],
["metaphor","метафора","noun","B2","general"],
["irony","іронія","noun","B2","general"],
["ambiguity","двозначність","noun","B2","general"],
["contradiction","суперечність","noun","B2","general"],
["compromise","компроміс","noun","B2","general"],
["consensus","консенсус","noun","B2","general"],
["dialogue","діалог","noun","B2","general"],
["rhetoric","риторика","noun","B2","general"],
["propaganda","пропаганда","noun","B2","general"],
["censorship","цензура","noun","B2","general"],

// ═══════════════ B2 VERBS ═══════════════
["implement","впроваджувати","verb","B2","work"],
["execute","виконувати","verb","B2","work"],
["evaluate","оцінювати","verb","B2","general"],
["assess","оцінювати (ситуацію)","verb","B2","general"],
["monitor","контролювати","verb","B2","work"],
["facilitate","сприяти","verb","B2","general"],
["coordinate","координувати","verb","B2","work"],
["integrate","інтегрувати","verb","B2","general"],
["transform","трансформувати","verb","B2","general"],
["restructure","реструктуризувати","verb","B2","work"],
["allocate","розподіляти","verb","B2","work"],
["utilise","використовувати","verb","B2","general"],
["optimise","оптимізувати","verb","B2","work"],
["streamline","оптимізовувати","verb","B2","work"],
["delegate","делегувати","verb","B2","work"],
["oversee","наглядати","verb","B2","work"],
["anticipate","передбачати","verb","B2","general"],
["forecast","прогнозувати","verb","B2","general"],
["project","прогнозувати (показники)","verb","B2","business"],
["sustain","підтримувати","verb","B2","general"],
["enhance","покращувати","verb","B2","general"],
["accelerate","прискорювати","verb","B2","general"],
["generate","генерувати","verb","B2","general"],
["derive","виводити","verb","B2","school"],
["demonstrate","демонструвати","verb","B2","general"],
["illustrate","ілюструвати","verb","B2","general"],
["clarify","уточнювати","verb","B2","communication"],
["elaborate","деталізувати","verb","B2","communication"],
["specify","уточнювати (деталі)","verb","B2","communication"],
["justify","обґрунтовувати","verb","B2","communication"],
["contradict","суперечити","verb","B2","communication"],
["manipulate","маніпулювати","verb","B2","general"],
["exploit","експлуатувати","verb","B2","general"],
["comply","дотримуватися","verb","B2","work"],
["regulate","регулювати","verb","B2","general"],
["restrict","обмежувати","verb","B2","general"],
["prohibit","забороняти","verb","B2","general"],
["enforce","примушувати (закон)","verb","B2","general"],
["advocate","відстоювати","verb","B2","general"],
["challenge","оспорювати","verb","B2","general"],
["acknowledge","визнавати","verb","B2","general"],
["distinguish","розрізняти","verb","B2","general"],
["perceive","сприймати","verb","B2","general"],
["interpret","інтерпретувати","verb","B2","general"],
["identify","визначати","verb","B2","general"],
["categorize","класифікувати","verb","B2","general"],
["quantify","кількісно вимірювати","verb","B2","school"],
["validate","підтверджувати","verb","B2","general"],
["verify","перевіряти (дані)","verb","B2","general"],
["scrutinize","уважно вивчати","verb","B2","general"],
["eliminate","усувати","verb","B2","general"],
["mitigate","пом'якшувати","verb","B2","general"],
["overcome","долати","verb","B2","general"],
["tackle","боротися з","verb","B2","general"],
["address","розглядати (проблему)","verb","B2","general"],
["resolve","розв'язувати","verb","B2","general"],
["negotiate","домовлятися","verb","B2","work"],
["collaborate","працювати спільно","verb","B2","work"],
["outsource","аутсорсити","verb","B2","work"],
["monetize","монетизувати","verb","B2","business"],
["scale","масштабувати","verb","B2","business"],
["disrupt","порушувати (ринок)","verb","B2","business"],
["pivot","змінювати напрямок","verb","B2","business"],
["launch","запускати","verb","B2","business"],
["rebrand","ребрендувати","verb","B2","business"],
["incentivize","стимулювати","verb","B2","business"],
["prioritise","розставляти пріоритети","verb","B2","work"],
["empower","надавати повноваження","verb","B2","work"],
["streamline","спрощувати процеси","verb","B2","work"],
["benchmark","зіставляти з еталоном","verb","B2","business"],
["depict","зображувати","verb","B2","hobby"],
["portray","описувати","verb","B2","hobby"],
["symbolise","символізувати","verb","B2","hobby"],
["characterise","характеризувати","verb","B2","general"],
["undermine","підривати","verb","B2","general"],
["reinforce","зміцнювати","verb","B2","general"],
["supplement","доповнювати","verb","B2","general"],
["compensate","компенсувати","verb","B2","general"],
["collaborate","співробітничати","verb","B2","work"],
["arbitrate","виступати арбітром","verb","B2","work"],

// ═══════════════ B2 ADJECTIVES ═══════════════
["sophisticated","витончений","adjective","B2","general"],
["comprehensive","всебічний","adjective","B2","general"],
["substantial","значний","adjective","B2","general"],
["considerable","суттєвий","adjective","B2","general"],
["fundamental","фундаментальний","adjective","B2","general"],
["inherent","притаманний","adjective","B2","general"],
["explicit","явний","adjective","B2","general"],
["implicit","неявний","adjective","B2","general"],
["ambiguous","неоднозначний","adjective","B2","general"],
["straightforward","зрозумілий","adjective","B2","general"],
["controversial","суперечливий","adjective","B2","general"],
["innovative","інноваційний","adjective","B2","business"],
["competitive","конкурентний","adjective","B2","business"],
["strategic","стратегічний","adjective","B2","business"],
["sustainable","стійкий","adjective","B2","nature"],
["renewable","відновлюваний","adjective","B2","nature"],
["toxic","токсичний","adjective","B2","nature"],
["vulnerable","вразливий","adjective","B2","general"],
["resilient","стійкий (до труднощів)","adjective","B2","general"],
["proactive","проактивний","adjective","B2","work"],
["objective","об'єктивний","adjective","B2","general"],
["subjective","суб'єктивний","adjective","B2","general"],
["abstract","абстрактний","adjective","B2","general"],
["concrete","конкретний","adjective","B2","general"],
["theoretical","теоретичний","adjective","B2","school"],
["empirical","емпіричний","adjective","B2","school"],
["quantitative","кількісний","adjective","B2","school"],
["qualitative","якісний","adjective","B2","school"],
["diverse","різноманітний","adjective","B2","general"],
["inclusive","інклюзивний","adjective","B2","general"],
["transparent","прозорий","adjective","B2","work"],
["accountable","підзвітний","adjective","B2","work"],
["ethical","етичний","adjective","B2","general"],
["biased","упереджений","adjective","B2","general"],
["neutral","нейтральний","adjective","B2","general"],
["rigorous","ретельний","adjective","B2","school"],
["thorough","ґрунтовний","adjective","B2","general"],
["meticulous","педантичний","adjective","B2","general"],
["excessive","надмірний","adjective","B2","general"],
["insufficient","недостатній","adjective","B2","general"],
["adequate","відповідний","adjective","B2","general"],
["obsolete","застарілий","adjective","B2","technology"],
["cutting-edge","передовий","adjective","B2","technology"],
["groundbreaking","новаторський","adjective","B2","general"],
["unprecedented","безпрецедентний","adjective","B2","general"],
["inevitable","неминучий","adjective","B2","general"],
["plausible","правдоподібний","adjective","B2","general"],
["feasible","здійсненний","adjective","B2","general"],
["viable","життєздатний","adjective","B2","business"],
["lucrative","вигідний","adjective","B2","business"],
["mutual","взаємний","adjective","B2","general"],
["reciprocal","взаємозалежний","adjective","B2","general"],
["concurrent","одночасний","adjective","B2","general"],
["subsequent","наступний","adjective","B2","general"],
["preliminary","попередній","adjective","B2","general"],
["integral","невід'ємний","adjective","B2","general"],
["marginal","незначний","adjective","B2","general"],
["acute","гострий","adjective","B2","health"],
["chronic","хронічний","adjective","B2","health"],
["infectious","інфекційний","adjective","B2","health"],
["cognitive","когнітивний","adjective","B2","health"],
["genetic","генетичний","adjective","B2","health"],

// ═══════════════ B2 ADVERBS ═══════════════
["consequently","отже","adverb","B2","general"],
["nevertheless","тим не менш","adverb","B2","general"],
["furthermore","крім того","adverb","B2","general"],
["moreover","до того ж","adverb","B2","general"],
["however","проте","adverb","B2","general"],
["therefore","тому","adverb","B2","general"],
["thus","таким чином","adverb","B2","general"],
["hence","звідси","adverb","B2","general"],
["likewise","так само","adverb","B2","general"],
["conversely","навпаки","adverb","B2","general"],
["arguably","мабуть","adverb","B2","general"],
["notably","зокрема","adverb","B2","general"],
["extensively","широко","adverb","B2","general"],
["substantially","суттєво","adverb","B2","general"],
["consistently","послідовно","adverb","B2","general"],
["predominantly","переважно","adverb","B2","general"],
["simultaneously","одночасно","adverb","B2","general"],
["inevitably","неминуче","adverb","B2","general"],
["accordingly","відповідно","adverb","B2","general"],
["deliberately","навмисно","adverb","B2","general"],
["explicitly","явно","adverb","B2","general"],
["inherently","по суті","adverb","B2","general"],
["ultimately","в кінцевому підсумку","adverb","B2","general"],
["presumably","вочевидь","adverb","B2","general"],
["technically","технічно","adverb","B2","general"],

];

// ── DEDUP & VALIDATE ────────────────────────────────────────────────────────
const seen = new Set();
const valid_pos = new Set(["verb","noun","adjective","adverb","number","conjunction","preposition","phrase"]);
const valid_levels = new Set(["A2","B1","B2"]);

const newWords = [];
let dupExist = 0, dupInternal = 0, badSchema = 0;

for (const [en,ua,pos,level,topic] of RAW) {
  const key = en.toLowerCase();
  if (existSet.has(key))     { dupExist++; continue; }
  if (seen.has(key))         { dupInternal++; continue; }
  if (!valid_pos.has(pos))   { badSchema++; console.warn('Bad pos:', en, pos); continue; }
  if (!valid_levels.has(level)) { badSchema++; console.warn('Bad level:', en, level); continue; }
  if (!en || !ua || !topic)  { badSchema++; console.warn('Missing field:', en); continue; }
  seen.add(key);
  newWords.push({en,ua,pos,level,topic});
}

console.log(`Candidates: ${RAW.length}`);
console.log(`Skipped (exist): ${dupExist}`);
console.log(`Skipped (internal dup): ${dupInternal}`);
console.log(`Skipped (bad schema): ${badSchema}`);
console.log(`New valid entries: ${newWords.length}`);

// Distribution check
const byLevel={}, byPos={};
newWords.forEach(w => {
  byLevel[w.level]=(byLevel[w.level]||0)+1;
  byPos[w.pos]=(byPos[w.pos]||0)+1;
});
console.log('New by level:', byLevel);
console.log('New by pos:', byPos);

if (newWords.length < 1500) {
  console.error(`ERROR: Only ${newWords.length} new words generated, need 1500`);
  process.exit(1);
}

// Take exactly 1500
const batch = newWords.slice(0, 1500);

// ── ASSIGN IDs & freqRanks ─────────────────────────────────────────────────
let nextId   = existing.length + 1;   // 1501
let nextFreq = Math.max(...existing.map(w=>w.freqRank)) + 1; // 1501

const entries = batch.map(w => ({
  id:       `w${String(nextId++).padStart(4,'0')}`,
  en:       w.en,
  ua:       w.ua,
  pos:      w.pos,
  level:    w.level,
  topic:    w.topic,
  freqRank: nextFreq++,
}));

// ── MERGE & SAVE ──────────────────────────────────────────────────────────
const merged = [...existing, ...entries];
console.log(`Total merged: ${merged.length}`);

// Final validation
const allEn = merged.map(w=>w.en.toLowerCase());
const allEnSet = new Set(allEn);
if (allEnSet.size !== merged.length) {
  console.error(`COLLISION: ${merged.length - allEnSet.size} duplicate en values in merged file`);
  process.exit(1);
}

fs.writeFileSync('./words.json', JSON.stringify(merged, null, 2));
console.log('words.json saved.');

// UA collision report (same pos+level)
const uaMap = {};
merged.forEach(w => {
  const k = `${w.pos}|${w.level}|${w.ua.trim().toLowerCase()}`;
  if (!uaMap[k]) uaMap[k]=[];
  uaMap[k].push(w.en);
});
const collisions = Object.entries(uaMap).filter(([,v])=>v.length>1);
console.log(`UA collisions (same pos+level): ${collisions.length}`);
collisions.slice(0,10).forEach(([k,v]) => console.log(' ',k,'→',v.join(', ')));
