'use strict';
const fs = require('fs');

const existing  = JSON.parse(fs.readFileSync('./words.json',    'utf8'));
const batch2    = JSON.parse(fs.readFileSync('./new_batch2.json','utf8'));
const batch3    = JSON.parse(fs.readFileSync('./new_batch3.json','utf8'));

const existSet  = new Set([
  ...existing.map(w=>w.en.toLowerCase()),
  ...batch2.map(w=>w.en.toLowerCase()),
  ...batch3.map(w=>w.en.toLowerCase()),
]);

// batch1 candidate list (the 530 valid ones from gen_words.js)
const B1_KEPT = [
"shoulder","elbow","knee","ankle","thumb","toe","chin","cheek","forehead","wrist","nail","lip","tooth","throat","chest","stomach","heel","palm","bone","skin","blood","muscle",
"pants","boot","sock","scarf","glove","suit","belt","pocket","sleeve","collar","zip","cap","swimsuit","uniform",
"pepper","oil","lemon","grape","strawberry","carrot","mushroom","pear","cherry","plum","watermelon","honey","jam","flour","cream","yogurt","noodle","snack","dessert","meal","dish","sausage","ham","bacon","bean","pea","corn","cabbage","cucumber","garlic","onion","pumpkin","peach","melon",
"ceiling","carpet","shelf","curtain","tap","shower","toilet","lamp","mirror","sofa","desk","pot","pan","oven","microwave","soap","towel","lock","lift","iron","vacuum cleaner","washing machine","plug","switch","bin","drawer","pillow","blanket","sheet","armchair","wardrobe",
"library","cinema","museum","church","bridge","building","gym","supermarket","post office","stadium","flat","fountain","square","port",
"lake","island","star","moon","earth","sand","fog","ice","storm","rainbow","wave","cave","valley","hill","cliff",
"duck","sheep","rabbit","bear","lion","tiger","elephant","monkey","cow","pig","horse","wolf","fox","snake","butterfly","bee","frog","deer","eagle","parrot",
"bike","truck","ferry","helicopter","subway",
"umbrella","wallet","ring","necklace","magazine","stamp","envelope","alarm","shape","photo","picture","coin","receipt","address","cable","battery",
"word","sentence","story","paragraph","subject","lesson","exam","grade","dictionary","textbook","blackboard","pencil","ruler","scissors","glue",
"game","song","music","team","ball","sport","player","match","score","goal","race","club","instrument",
"baby","neighbor","guest","crowd",
"jump","run","sit","stand","fall","carry","hold","bring","move","turn","push","pull","drop","pack","meet","visit","play","sing","dance","paint","swim","drive","fly","climb","smile","laugh","cry","miss","wear","cut","break","fix","build","grow","plant","hang","heat","cool","pour","mix","boil","fry","bake","save","lose","win","practice","hurry","relax","return","arrive","enter","exit","knock","point","touch","catch","throw","lift","bite","kick","rent","borrow","lend","choose","collect","invite","celebrate","surprise","promise","agree","refuse","follow","check","ride","share","earn","spend","suggest",
"tall","thin","fat","cool","sour","salty","spicy","delicious","hungry","thirsty","loud","closed","same","sunny","cloudy","rainy","windy","snowy","foggy","wet","wide","narrow","deep","shallow","round","straight","bright","boring","funny","cute","ugly","strange","perfect","terrible","wonderful","amazing","delicate","flat","frozen","fresh","raw","cooked","ripe","broken","lost","alone","clever","lazy","polite","rude","shy","brave","early","late","sharp",
"slowly","quickly","quietly","loudly","carefully","suddenly","together","outside","inside","upstairs","downstairs","enough","away","ahead","instead",
];
for (const w of B1_KEPT) existSet.add(w.toLowerCase());

console.log('Total excluded so far:', existSet.size);

const RAW4 = [
// ── B1 NOUNS (domain-specific) ──────────────────────────────────────────────
["headline","заголовок","noun","B1","communication"],
["broadcast","мовлення","noun","B1","communication"],
["advertisement","реклама","noun","B1","communication"],
["slogan","слоган","noun","B1","communication"],
["column","колонка (у газеті)","noun","B1","communication"],
["editorial","передова стаття","noun","B1","communication"],
["journalist","журналіст","noun","B1","communication"],
["anchor","ведучий новин","noun","B1","communication"],
["episode","епізод","noun","B1","hobby"],
["documentary","документальний фільм","noun","B1","hobby"],
["animation","мультиплікація","noun","B1","hobby"],
["rehearsal","репетиція","noun","B1","hobby"],
["backstage","закулісся","noun","B1","hobby"],
["gallery","галерея","noun","B1","hobby"],
["exhibition","виставка","noun","B1","hobby"],
["sculpture","скульптура","noun","B1","hobby"],
["portrait","портрет","noun","B1","hobby"],
["landscape","пейзаж","noun","B1","hobby"],
["novel","роман","noun","B1","hobby"],
["thriller","трилер","noun","B1","hobby"],
["biography","біографія","noun","B1","hobby"],
["poetry","поезія","noun","B1","hobby"],
["stanza","строфа","noun","B1","hobby"],
["rhythm","ритм","noun","B1","hobby"],
["lyrics","слова пісні","noun","B1","hobby"],
["chorus","приспів","noun","B1","hobby"],
["orchestra","оркестр","noun","B1","hobby"],
["conductor","диригент","noun","B1","hobby"],
["rehearse","репетирувати","verb","B1","hobby"],
["applause","оплески","noun","B1","hobby"],
["spectator","глядач","noun","B1","hobby"],
["audience","аудиторія","noun","B1","hobby"],
["critic","критик","noun","B1","hobby"],
["review","рецензія","noun","B1","hobby"],
["masterpiece","шедевр","noun","B1","hobby"],
["plot","сюжет","noun","B1","hobby"],
["character","персонаж","noun","B1","hobby"],
["dialogue","діалог","noun","B1","hobby"],
["sequel","продовження","noun","B1","hobby"],
["chapter","розділ","noun","B1","hobby"],
["genre","жанр","noun","B1","hobby"],
["fiction","белетристика","noun","B1","hobby"],
["fantasy","фантастика","noun","B1","hobby"],
["thriller","детектив","noun","B1","hobby"],
["graphic novel","графічний роман","noun","B1","hobby"],
["architect","архітектор","noun","B1","work"],
["surgeon","хірург","noun","B1","health"],
["pharmacist","фармацевт","noun","B1","health"],
["therapist","психотерапевт","noun","B1","health"],
["nutritionist","дієтолог","noun","B1","health"],
["paramedic","парамедик","noun","B1","health"],
["mechanic","механік","noun","B1","work"],
["plumber","сантехнік","noun","B1","work"],
["electrician","електрик","noun","B1","work"],
["carpenter","тесляр","noun","B1","work"],
["locksmith","слюсар","noun","B1","work"],
["cashier","касир","noun","B1","work"],
["receptionist","адміністратор","noun","B1","work"],
["secretary","секретар","noun","B1","work"],
["accountant","бухгалтер","noun","B1","work"],
["librarian","бібліотекар","noun","B1","work"],
["security guard","охоронець","noun","B1","work"],
["postman","листоноша","noun","B1","work"],
["firefighter","пожежник","noun","B1","work"],
["ambulance","швидка допомога","noun","B1","health"],
["siren","сирена","noun","B1","general"],
["emergency","надзвичайна ситуація","noun","B1","health"],
["epidemic","епідемія","noun","B1","health"],
["vaccination","вакцинація","noun","B1","health"],
["dose","доза","noun","B1","health"],
["capsule","капсула","noun","B1","health"],
["tablet","таблетка","noun","B1","health"],
["injection","ін'єкція","noun","B1","health"],
["surgeon","хірург","noun","B1","health"],
["anaesthetic","анестезія","noun","B1","health"],
["recovery","одужання","noun","B1","health"],
["ward","палата","noun","B1","health"],
["prescription","рецепт","noun","B1","health"],
["symptom","симптом","noun","B1","health"],
["diagnosis","діагноз","noun","B1","health"],
["operation","операція","noun","B1","health"],
["bandage","бинт","noun","B1","health"],
["syringe","шприц","noun","B1","health"],
["thermometer","термометр","noun","B1","health"],
["scale","терези","noun","B1","health"],
["clinic","клініка","noun","B1","health"],
["appointment","прийом у лікаря","noun","B1","health"],
["allergy","алергія","noun","B1","health"],
["rash","висип","noun","B1","health"],
["bruise","синяк","noun","B1","health"],
["wound","рана","noun","B1","health"],
["scar","шрам","noun","B1","health"],
["blister","мозоля","noun","B1","health"],
["fracture","перелом","noun","B1","health"],
["sprain","розтягнення","noun","B1","health"],
["concussion","струс мозку","noun","B1","health"],
["insomnia","безсоння","noun","B1","health"],
["migraine","мігрень","noun","B1","health"],
["anxiety","тривога","noun","B1","health"],
["depression","депресія","noun","B1","health"],
["obesity","ожиріння","noun","B1","health"],
["cholesterol","холестерин","noun","B1","health"],
["calorie","калорія","noun","B1","health"],
["diet","дієта","noun","B1","health"],
["enzyme","фермент","noun","B1","health"],
["vitamin","вітамін","noun","B1","health"],
["mineral","мінерал","noun","B1","health"],
["protein","білок","noun","B1","health"],
["carbohydrate","вуглевод","noun","B1","health"],
["fat","жир","noun","B1","health"],
["fibre","клітковина","noun","B1","health"],
["calorie","калорія","noun","B1","health"],
["nutrient","поживна речовина","noun","B1","health"],
["supplement","харчова добавка","noun","B1","health"],
["immunity","імунітет","noun","B1","health"],
["antibody","антитіло","noun","B1","health"],
["virus","вірус","noun","B1","health"],
["bacteria","бактерія","noun","B1","health"],
["infection","інфекція","noun","B1","health"],
["inflammation","запалення","noun","B1","health"],
["fever","жар","noun","B1","health"],
["cough","кашель","noun","B1","health"],
["cold","застуда","noun","B1","health"],
["flu","грип","noun","B1","health"],
["allergy","алергія","noun","B1","health"],
// B1 technology
["software","програмне забезпечення","noun","B1","technology"],
["hardware","апаратне забезпечення","noun","B1","technology"],
["processor","процесор","noun","B1","technology"],
["memory","пам'ять (RAM)","noun","B1","technology"],
["storage","сховище даних","noun","B1","technology"],
["bandwidth","пропускна здатність","noun","B1","technology"],
["connection","з'єднання","noun","B1","technology"],
["router","маршрутизатор","noun","B1","technology"],
["modem","модем","noun","B1","technology"],
["server","сервер","noun","B1","technology"],
["database","база даних","noun","B1","technology"],
["algorithm","алгоритм","noun","B1","technology"],
["code","код","noun","B1","technology"],
["bug","помилка (програмна)","noun","B1","technology"],
["update","оновлення","noun","B1","technology"],
["backup","резервна копія","noun","B1","technology"],
["virus","комп'ютерний вірус","noun","B1","technology"],
["firewall","брандмауер","noun","B1","technology"],
["encryption","шифрування","noun","B1","technology"],
["download","завантаження","noun","B1","technology"],
["upload","завантаження (на сервер)","noun","B1","technology"],
["browser","браузер","noun","B1","technology"],
["cursor","курсор","noun","B1","technology"],
["pixel","піксель","noun","B1","technology"],
["resolution","роздільна здатність","noun","B1","technology"],
["interface","інтерфейс","noun","B1","technology"],
["menu","меню","noun","B1","technology"],
["icon","іконка","noun","B1","technology"],
["folder","папка","noun","B1","technology"],
["file","файл","noun","B1","technology"],
["extension","розширення (файлу)","noun","B1","technology"],
["format","формат","noun","B1","technology"],
["platform","платформа","noun","B1","technology"],
["application","застосунок","noun","B1","technology"],
// B1 environment
["deforestation","вирубка лісів","noun","B1","nature"],
["reforestation","відновлення лісів","noun","B1","nature"],
["habitat","середовище існування","noun","B1","nature"],
["ecosystem","екосистема","noun","B1","nature"],
["species","вид (тварини)","noun","B1","nature"],
["extinction","вимирання","noun","B1","nature"],
["pollution","забруднення","noun","B1","nature"],
["emission","викид","noun","B1","nature"],
["renewable","відновлювальна (енергія)","noun","B1","nature"],
["solar panel","сонячна панель","noun","B1","nature"],
["turbine","турбіна","noun","B1","nature"],
["reservoir","водосховище","noun","B1","nature"],
["drought","посуха","noun","B1","nature"],
["flood","повінь","noun","B1","nature"],
["earthquake","землетрус","noun","B1","nature"],
["hurricane","ураган","noun","B1","nature"],
["tornado","торнадо","noun","B1","nature"],
["avalanche","лавина","noun","B1","nature"],
["wildlife","дика природа","noun","B1","nature"],
["predator","хижак","noun","B1","nature"],
["prey","здобич","noun","B1","nature"],
["migration","міграція (птахів)","noun","B1","nature"],
["nest","гніздо","noun","B1","nature"],
["burrow","нора","noun","B1","nature"],
["thorn","колючка","noun","B1","nature"],
["petal","пелюстка","noun","B1","nature"],
["pollen","пилок","noun","B1","nature"],
["bark","кора дерева","noun","B1","nature"],
["moss","мох","noun","B1","nature"],
["algae","водорості","noun","B1","nature"],
["plankton","планктон","noun","B1","nature"],
["coral","корал","noun","B1","nature"],
["swamp","болото","noun","B1","nature"],
["marsh","трясовина","noun","B1","nature"],
// B1 travel
["departure","відправлення","noun","B1","travel"],
["arrival","прибуття","noun","B1","travel"],
["layover","пересадка","noun","B1","travel"],
["check-in","реєстрація (авіа)","noun","B1","travel"],
["boarding","посадка","noun","B1","travel"],
["runway","злітно-посадкова смуга","noun","B1","travel"],
["terminal","термінал (аеропорт)","noun","B1","travel"],
["customs","митниця","noun","B1","travel"],
["baggage","багаж","noun","B1","travel"],
["cabin","салон літака","noun","B1","travel"],
["turbulence","турбулентність","noun","B1","travel"],
["altitude","висота польоту","noun","B1","travel"],
["navigation","навігація","noun","B1","travel"],
["route","маршрут","noun","B1","travel"],
["itinerary","план подорожі","noun","B1","travel"],
["excursion","екскурсія","noun","B1","travel"],
["accommodation","проживання","noun","B1","travel"],
["hostel","хостел","noun","B1","travel"],
["campsite","кемпінг","noun","B1","travel"],
["brochure","брошура","noun","B1","travel"],
["currency","валюта","noun","B1","travel"],
["exchange rate","обмінний курс","noun","B1","money"],
["souvenir","сувенір","noun","B1","travel"],
["guidebook","путівник","noun","B1","travel"],
// B1 money/business
["transaction","транзакція","noun","B1","money"],
["receipt","квитанція","noun","B1","money"],
["invoice","рахунок-фактура","noun","B1","money"],
["installment","розстрочка","noun","B1","money"],
["commission","комісія","noun","B1","money"],
["bonus","бонус","noun","B1","money"],
["turnover","оборот","noun","B1","business"],
["profit","прибуток","noun","B1","business"],
["loss","збиток","noun","B1","business"],
["revenue","виручка","noun","B1","business"],
["interest","відсотки","noun","B1","money"],
["loan","позика","noun","B1","money"],
["repayment","погашення боргу","noun","B1","money"],
["capital","капітал","noun","B1","money"],
["portfolio","портфель (активів)","noun","B1","money"],
["shareholder","акціонер","noun","B1","business"],
["stakeholder","зацікавлена сторона","noun","B1","business"],
["merger","злиття (компаній)","noun","B1","business"],
["acquisition","поглинання (компанії)","noun","B1","business"],
["launch","запуск (продукту)","noun","B1","business"],
["startup","стартап","noun","B1","business"],
["pitch","презентація (стартапу)","noun","B1","business"],
["target","ціль","noun","B1","business"],
["milestone","ключова позначка","noun","B1","business"],
["deadline","крайній термін","noun","B1","work"],
["budget","бюджет","noun","B1","money"],
["forecast","прогноз","noun","B1","business"],
["competitor","конкурент","noun","B1","business"],
["market share","частка ринку","noun","B1","business"],
["customer","клієнт","noun","B1","business"],
["retailer","роздрібний продавець","noun","B1","business"],
["wholesaler","оптовий торговець","noun","B1","business"],
["supplier","постачальник","noun","B1","business"],
["distribution","розподіл","noun","B1","business"],
["logistics","логістика","noun","B1","business"],
["warehouse","склад","noun","B1","business"],
["inventory","інвентар","noun","B1","business"],
["shipment","поставка","noun","B1","business"],
// B1 home/food
["recipe","рецепт","noun","B1","food"],
["ingredient","інгредієнт","noun","B1","food"],
["portion","порція","noun","B1","food"],
["seasoning","приправа","noun","B1","food"],
["condiment","приправа (за смаком)","noun","B1","food"],
["marinade","маринад","noun","B1","food"],
["batter","тісто (рідке)","noun","B1","food"],
["dough","тісто","noun","B1","food"],
["crust","скоринка","noun","B1","food"],
["filling","начинка","noun","B1","food"],
["sauce","соус","noun","B1","food"],
["broth","бульйон","noun","B1","food"],
["stew","рагу","noun","B1","food"],
["roast","смажене м'ясо","noun","B1","food"],
["grill","решітка для гриля","noun","B1","food"],
["pastry","здобна випічка","noun","B1","food"],
["muffin","кекс","noun","B1","food"],
["waffle","вафля","noun","B1","food"],
["pudding","пудинг","noun","B1","food"],
["cookie","печиво","noun","B1","food"],
["brownie","брауні","noun","B1","food"],
["smoothie","смузі","noun","B1","food"],
["latte","лате","noun","B1","food"],
["cappuccino","капучино","noun","B1","food"],
["espresso","еспресо","noun","B1","food"],
["herbal tea","трав'яний чай","noun","B1","food"],
["sparkling water","газована вода","noun","B1","food"],
["lemonade","лимонад","noun","B1","food"],
["milkshake","молочний коктейль","noun","B1","food"],
["leftovers","залишки їжі","noun","B1","food"],
["takeaway","їжа на виніс","noun","B1","food"],
["tip","чайові","noun","B1","food"],
["buffet","шведський стіл","noun","B1","food"],
["menu","меню (ресторан)","noun","B1","food"],
["waiter","офіціант","noun","B1","food"],
["chef","шеф-кухар","noun","B1","food"],
["cuisine","кухня (тип)","noun","B1","food"],
["restaurant","ресторан","noun","B1","food"],
["cafeteria","кафетерій","noun","B1","food"],
// B1 verbs additional
["diagnose","ставити діагноз","verb","B1","health"],
["treat","лікувати","verb","B1","health"],
["prescribe","призначати ліки","verb","B1","health"],
["vaccinate","вакцинувати","verb","B1","health"],
["recover","одужувати","verb","B1","health"],
["operate","проводити операцію","verb","B1","health"],
["download","завантажувати","verb","B1","technology"],
["upload","завантажувати на сервер","verb","B1","technology"],
["install","встановлювати","verb","B1","technology"],
["reboot","перезавантажувати","verb","B1","technology"],
["stream","стрімити","verb","B1","technology"],
["click","клікати","verb","B1","technology"],
["scroll","прокручувати","verb","B1","technology"],
["zoom","збільшувати","verb","B1","technology"],
["crop","обрізати (фото)","verb","B1","technology"],
["filter","фільтрувати","verb","B1","technology"],
["tag","позначати","verb","B1","technology"],
["post","публікувати","verb","B1","communication"],
["share","ділитися (соцмережі)","verb","B1","communication"],
["like","лайкати","verb","B1","communication"],
["block","блокувати","verb","B1","communication"],
["report","поскаржитися","verb","B1","communication"],
["forward","пересилати","verb","B1","communication"],
["reply","відповідати на повідомлення","verb","B1","communication"],
["mute","вимкнути звук","verb","B1","communication"],
["swap","обмінювати","verb","B1","general"],
["merge","об'єднувати","verb","B1","business"],
["outsource","передавати на аутсорс","verb","B1","business"],
["negotiate","проводити переговори","verb","B1","business"],
["audit","проводити аудит","verb","B1","business"],
["launch","запускати (продукт)","verb","B1","business"],
["pitch","презентувати (ідею)","verb","B1","business"],
["draft","складати чернетку","verb","B1","work"],
["proofread","перевіряти (текст)","verb","B1","school"],
["revise","переглядати (текст)","verb","B1","school"],
["brainstorm","мозковий штурм","verb","B1","work"],
["delegate","делегувати","verb","B1","work"],
["supervise","контролювати","verb","B1","work"],
["evaluate","оцінювати","verb","B1","work"],
["coordinate","координувати","verb","B1","work"],
["implement","впроваджувати","verb","B1","work"],
["monitor","відстежувати","verb","B1","work"],
["deploy","розгортати","verb","B1","technology"],
["integrate","інтегрувати","verb","B1","technology"],
["test","тестувати","verb","B1","technology"],
["debug","налагоджувати","verb","B1","technology"],
["automate","автоматизувати","verb","B1","technology"],
// B1 adjectives additional
["experienced","досвідчений","adjective","B1","work"],
["motivated","мотивований","adjective","B1","general"],
["confident","впевнений","adjective","B1","general"],
["independent","самостійний","adjective","B1","general"],
["responsible","відповідальний","adjective","B1","general"],
["creative","творчий","adjective","B1","general"],
["flexible","гнучкий","adjective","B1","general"],
["productive","продуктивний","adjective","B1","work"],
["efficient","ефективний","adjective","B1","work"],
["competitive","конкурентоспроможний","adjective","B1","business"],
["profitable","прибутковий","adjective","B1","business"],
["sustainable","стійкий (екологічно)","adjective","B1","nature"],
["renewable","відновлюваний","adjective","B1","nature"],
["recyclable","придатний до переробки","adjective","B1","nature"],
["biodegradable","біорозкладний","adjective","B1","nature"],
["organic","органічний","adjective","B1","food"],
["nutritious","поживний","adjective","B1","health"],
["balanced","збалансований","adjective","B1","health"],
["active","активний","adjective","B1","sport"],
["fit","у формі","adjective","B1","sport"],
["athletic","атлетичний","adjective","B1","sport"],
["injured","травмований","adjective","B1","sport"],
["disabled","з обмеженими можливостями","adjective","B1","health"],
["chronic","хронічний","adjective","B1","health"],
["severe","тяжкий (симптом)","adjective","B1","health"],
["mild","легкий (симптом)","adjective","B1","health"],
["infectious","інфекційний","adjective","B1","health"],
["toxic","токсичний","adjective","B1","health"],
["urgent","терміновий","adjective","B1","general"],
["necessary","необхідний","adjective","B1","general"],
["optional","необов'язковий","adjective","B1","general"],
["practical","практичний","adjective","B1","general"],
["logical","логічний","adjective","B1","general"],
["accurate","точний","adjective","B1","general"],
["fluent","вільний (мова)","adjective","B1","school"],
["formal","офіційний","adjective","B1","communication"],
["informal","неформальний","adjective","B1","communication"],
["digital","цифровий","adjective","B1","technology"],
["virtual","віртуальний","adjective","B1","technology"],
["wireless","бездротовий","adjective","B1","technology"],
["compatible","сумісний","adjective","B1","technology"],
["portable","портативний","adjective","B1","technology"],
["affordable","доступний (ціна)","adjective","B1","money"],
["reliable","надійний","adjective","B1","general"],
["durable","міцний","adjective","B1","general"],
["convenient","зручний","adjective","B1","general"],
["adequate","достатній","adjective","B1","general"],
["suitable","підходящий","adjective","B1","general"],
// B1 adverbs additional
["frequently","часто","adverb","B1","time"],
["regularly","регулярно","adverb","B1","time"],
["occasionally","іноді","adverb","B1","time"],
["continuously","безперервно","adverb","B1","time"],
["briefly","коротко","adverb","B1","time"],
["permanently","постійно","adverb","B1","time"],
["temporarily","тимчасово","adverb","B1","time"],
["gradually","поступово","adverb","B1","general"],
["rapidly","швидко","adverb","B1","general"],
["apparently","мабуть","adverb","B1","general"],
["obviously","очевидно","adverb","B1","general"],
["clearly","чітко","adverb","B1","general"],
["actually","насправді","adverb","B1","general"],
["basically","по суті","adverb","B1","general"],
["generally","загалом","adverb","B1","general"],
["typically","зазвичай","adverb","B1","general"],
["significantly","значно","adverb","B1","general"],
["particularly","зокрема","adverb","B1","general"],
["especially","особливо","adverb","B1","general"],
["fortunately","на щастя","adverb","B1","general"],
["unfortunately","на жаль","adverb","B1","general"],
["surprisingly","дивовижно","adverb","B1","general"],
["immediately","негайно","adverb","B1","time"],
["eventually","зрештою","adverb","B1","time"],
["previously","раніше","adverb","B1","time"],
["recently","нещодавно","adverb","B1","time"],
["currently","зараз","adverb","B1","time"],
["approximately","приблизно","adverb","B1","general"],
["nearly","майже","adverb","B1","general"],
["hardly","ледь","adverb","B1","general"],
["definitely","безумовно","adverb","B1","general"],
["certainly","звичайно","adverb","B1","general"],
["probably","мабуть","adverb","B1","general"],
["mainly","головним чином","adverb","B1","general"],
["mostly","переважно","adverb","B1","general"],

// ── B2 WORDS ─────────────────────────────────────────────────────────────────
["consortium","консорціум","noun","B2","business"],
["procurement","закупівля","noun","B2","business"],
["collateral","застава","noun","B2","money"],
["arbitrage","арбітраж","noun","B2","money"],
["leverage","кредитне плече","noun","B2","money"],
["liquidity","ліквідність","noun","B2","money"],
["solvency","платоспроможність","noun","B2","money"],
["depreciation","амортизація","noun","B2","money"],
["amortization","погашення (боргу)","noun","B2","money"],
["volatility","волатильність","noun","B2","money"],
["speculation","спекуляція","noun","B2","money"],
["hedge","хеджування","noun","B2","money"],
["securities","цінні папери","noun","B2","money"],
["derivatives","деривативи","noun","B2","money"],
["portfolio","інвестиційний портфель","noun","B2","money"],
["microeconomics","мікроекономіка","noun","B2","money"],
["macroeconomics","макроекономіка","noun","B2","money"],
["keynesianism","кейнсіанство","noun","B2","money"],
["monetarism","монетаризм","noun","B2","money"],
["oligopoly","олігополія","noun","B2","business"],
["duopoly","дуополія","noun","B2","business"],
["cartel","картель","noun","B2","business"],
["paradigm","парадигма","noun","B2","school"],
["hypothesis","гіпотеза","noun","B2","school"],
["methodology","методологія","noun","B2","school"],
["dissertation","дисертація","noun","B2","school"],
["thesis","теза","noun","B2","school"],
["symposium","симпозіум","noun","B2","school"],
["anthology","антологія","noun","B2","hobby"],
["manuscript","рукопис","noun","B2","hobby"],
["allegory","алегорія","noun","B2","hobby"],
["metaphor","метафора","noun","B2","hobby"],
["symbolism","символізм","noun","B2","hobby"],
["irony","іронія","noun","B2","hobby"],
["satire","сатира","noun","B2","hobby"],
["narrative","оповідь","noun","B2","hobby"],
["protagonist","протагоніст","noun","B2","hobby"],
["antagonist","антагоніст","noun","B2","hobby"],
["archetype","архетип","noun","B2","hobby"],
["ambiguity","неоднозначність","noun","B2","general"],
["nuance","нюанс","noun","B2","general"],
["discrepancy","розбіжність","noun","B2","general"],
["inconsistency","непослідовність","noun","B2","general"],
["contradiction","суперечність","noun","B2","general"],
["paradox","парадокс","noun","B2","general"],
["dilemma","дилема","noun","B2","general"],
["propaganda","пропаганда","noun","B2","general"],
["rhetoric","риторика","noun","B2","communication"],
["manifesto","маніфест","noun","B2","general"],
["ideology","ідеологія","noun","B2","general"],
["sovereignty","суверенітет","noun","B2","general"],
["jurisdiction","юрисдикція","noun","B2","general"],
["tribunal","трибунал","noun","B2","general"],
["statute","статут","noun","B2","general"],
["legislation","законодавство","noun","B2","general"],
["parliament","парламент","noun","B2","general"],
["diplomacy","дипломатія","noun","B2","general"],
["ambassador","посол","noun","B2","general"],
["embassy","посольство","noun","B2","general"],
["refugee","біженець","noun","B2","general"],
["asylum","притулок","noun","B2","general"],
["humanitarian","гуманітарний","noun","B2","general"],
["genocide","геноцид","noun","B2","general"],
["colonialism","колоніалізм","noun","B2","general"],
["imperialism","імперіалізм","noun","B2","general"],
["dictatorship","диктатура","noun","B2","general"],
["totalitarianism","тоталітаризм","noun","B2","general"],
["utopia","утопія","noun","B2","general"],
["dystopia","дистопія","noun","B2","general"],
["cynicism","цинізм","noun","B2","general"],
["nihilism","нігілізм","noun","B2","general"],
["existentialism","екзистенціалізм","noun","B2","general"],
["pragmatism","прагматизм","noun","B2","general"],
["relativism","релятивізм","noun","B2","general"],
["empiricism","емпіризм","noun","B2","school"],
["rationalism","раціоналізм","noun","B2","school"],
["scepticism","скептицизм","noun","B2","school"],
["perception","сприйняття","noun","B2","school"],
["consciousness","свідомість","noun","B2","school"],
["intuition","інтуїція","noun","B2","school"],
["subjectivity","суб'єктивність","noun","B2","school"],
["objectivity","об'єктивність","noun","B2","school"],
["epistemology","гносеологія","noun","B2","school"],
["ontology","онтологія","noun","B2","school"],
["ethics","етика","noun","B2","school"],
["aesthetics","естетика","noun","B2","school"],
["neuroplasticity","нейропластичність","noun","B2","health"],
["genome","геном","noun","B2","health"],
["epigenetics","епігенетика","noun","B2","health"],
["microbiome","мікробіом","noun","B2","health"],
["cortisol","кортизол","noun","B2","health"],
["serotonin","серотонін","noun","B2","health"],
["dopamine","дофамін","noun","B2","health"],
["adrenaline","адреналін","noun","B2","health"],
["metabolism","метаболізм","noun","B2","health"],
["homeostasis","гомеостаз","noun","B2","health"],
["resilience","стресостійкість","noun","B2","health"],
["burnout","вигорання","noun","B2","health"],
["trauma","травма","noun","B2","health"],
["gaslighting","газлайтинг","noun","B2","emotions"],
["empathy","емпатія","noun","B2","emotions"],
["narcissism","нарцисизм","noun","B2","emotions"],
["altruism","альтруїзм","noun","B2","emotions"],
["stoicism","стоїцизм","noun","B2","emotions"],
["misogyny","мізогінія","noun","B2","emotions"],
["prejudice","упередженість","noun","B2","general"],
["discrimination","дискримінація","noun","B2","general"],
["stereotype","стереотип","noun","B2","general"],
["bias","упередженість","noun","B2","general"],
["stigma","стигма","noun","B2","general"],
["tokenism","формальне включення меншин","noun","B2","general"],
["intersectionality","перетин соціальних факторів","noun","B2","general"],
["gentrification","джентрифікація","noun","B2","general"],
["segregation","сегрегація","noun","B2","general"],
["assimilation","асиміляція","noun","B2","general"],
["multiculturalism","мультикультуралізм","noun","B2","general"],
["cosmopolitanism","космополітизм","noun","B2","general"],
["nationalism","націоналізм","noun","B2","general"],
["globalization","глобалізація","noun","B2","general"],
["neoliberalism","неолібералізм","noun","B2","general"],
// B2 verbs
["conceptualize","концептуалізувати","verb","B2","school"],
["operationalize","операціоналізувати","verb","B2","school"],
["hypothesize","висувати гіпотезу","verb","B2","school"],
["postulate","постулювати","verb","B2","school"],
["extrapolate","екстраполювати","verb","B2","school"],
["interpolate","інтерполювати","verb","B2","school"],
["corroborate","підтверджувати","verb","B2","school"],
["substantiate","обгрунтовувати","verb","B2","school"],
["circumvent","обходити","verb","B2","general"],
["undermine","підривати","verb","B2","general"],
["exacerbate","погіршувати","verb","B2","general"],
["mitigate","пом'якшувати","verb","B2","general"],
["alleviate","полегшувати","verb","B2","general"],
["perpetuate","увічнювати","verb","B2","general"],
["propagate","поширювати","verb","B2","general"],
["disseminate","поширювати знання","verb","B2","communication"],
["facilitate","сприяти","verb","B2","general"],
["impede","перешкоджати","verb","B2","general"],
["obstruct","блокувати","verb","B2","general"],
["catalyze","каталізувати","verb","B2","general"],
["galvanize","активізувати","verb","B2","general"],
["polarize","поляризувати","verb","B2","general"],
["marginalize","маргіналізувати","verb","B2","general"],
["disenfranchise","позбавляти прав","verb","B2","general"],
["vilify","очорнювати","verb","B2","general"],
["demonize","демонізувати","verb","B2","general"],
["legitimize","легітимізувати","verb","B2","general"],
["rationalize","раціоналізувати","verb","B2","general"],
["quantify","кількісно оцінювати","verb","B2","school"],
["qualify","уточнювати","verb","B2","school"],
["stipulate","передбачати","verb","B2","general"],
["mandate","зобов'язувати","verb","B2","general"],
["arbitrate","виступати арбітром","verb","B2","general"],
["mediate","виступати посередником","verb","B2","general"],
["negotiate","домовлятися","verb","B2","business"],
["speculate","спекулювати","verb","B2","money"],
["diversify","диверсифікувати","verb","B2","business"],
["consolidate","консолідувати","verb","B2","business"],
["liquidate","ліквідовувати","verb","B2","business"],
["default","не виконувати зобов'язань","verb","B2","money"],
["leverage","використовувати важіль","verb","B2","business"],
["hedge","хеджувати","verb","B2","money"],
["devalue","девальвувати","verb","B2","money"],
// B2 adjectives
["multifaceted","багатогранний","adjective","B2","general"],
["far-reaching","далекосяжний","adjective","B2","general"],
["thought-provoking","що змушує задуматися","adjective","B2","general"],
["self-evident","очевидний","adjective","B2","general"],
["counterintuitive","контрінтуїтивний","adjective","B2","general"],
["disproportionate","непропорційний","adjective","B2","general"],
["arbitrary","довільний","adjective","B2","general"],
["erratic","непостійний","adjective","B2","general"],
["coherent","узгоджений","adjective","B2","general"],
["incoherent","незв'язний","adjective","B2","general"],
["tangible","відчутний","adjective","B2","general"],
["intangible","нематеріальний","adjective","B2","general"],
["quantifiable","вимірюваний","adjective","B2","school"],
["qualitative","якісний","adjective","B2","school"],
["quantitative","кількісний","adjective","B2","school"],
["empirical","емпіричний","adjective","B2","school"],
["theoretical","теоретичний","adjective","B2","school"],
["hypothetical","гіпотетичний","adjective","B2","school"],
["speculative","умоглядний","adjective","B2","school"],
["inconclusive","без остаточних висновків","adjective","B2","school"],
["replicable","відтворний","adjective","B2","school"],
["longitudinal","поздовжній","adjective","B2","school"],
["statistically significant","статистично значущий","adjective","B2","school"],
["peer-reviewed","рецензований","adjective","B2","school"],
["tenure","безстроковий (посада)","adjective","B2","work"],
["contentious","суперечливий","adjective","B2","general"],
["divisive","що вносить розкол","adjective","B2","general"],
["polarizing","поляризуючий","adjective","B2","general"],
["radical","радикальний","adjective","B2","general"],
["reactionary","реакційний","adjective","B2","general"],
["progressive","прогресивний","adjective","B2","general"],
["conservative","консервативний","adjective","B2","general"],
["liberal","ліберальний","adjective","B2","general"],
["authoritarian","авторитарний","adjective","B2","general"],
["egalitarian","егалітарний","adjective","B2","general"],
["secular","світський","adjective","B2","general"],
["theocratic","теократичний","adjective","B2","general"],
["bureaucratic","бюрократичний","adjective","B2","general"],
["oligarchic","олігархічний","adjective","B2","general"],
["despotic","деспотичний","adjective","B2","general"],
["systemic","системний","adjective","B2","general"],
["structural","структурний","adjective","B2","general"],
["institutional","інституційний","adjective","B2","general"],
["hierarchical","ієрархічний","adjective","B2","general"],
["decentralized","децентралізований","adjective","B2","general"],
["asymmetric","асиметричний","adjective","B2","general"],
["synergistic","синергетичний","adjective","B2","general"],
["transformative","трансформаційний","adjective","B2","general"],
["disruptive","руйнівний","adjective","B2","technology"],
["exponential","експоненційний","adjective","B2","general"],
["holistic","цілісний","adjective","B2","general"],
["nuanced","тонкий","adjective","B2","general"],
["polarized","поляризований","adjective","B2","general"],
["entrenched","укорінений","adjective","B2","general"],
["pervasive","всеохопний","adjective","B2","general"],
// B2 adverbs
["paradoxically","парадоксально","adverb","B2","general"],
["rhetorically","риторично","adverb","B2","general"],
["ideologically","ідеологічно","adverb","B2","general"],
["diplomatically","дипломатично","adverb","B2","general"],
["constitutionally","конституційно","adverb","B2","general"],
["institutionally","інституційно","adverb","B2","general"],
["empirically","емпірично","adverb","B2","school"],
["theoretically","теоретично","adverb","B2","school"],
["conceptually","концептуально","adverb","B2","school"],
["statistically","статистично","adverb","B2","school"],
["disproportionately","непропорційно","adverb","B2","general"],
["overwhelmingly","переважно","adverb","B2","general"],
["unanimously","одностайно","adverb","B2","general"],
["intrinsically","властиво","adverb","B2","general"],
["extrinsically","зовнішньо","adverb","B2","general"],
["sequentially","послідовно","adverb","B2","general"],
["simultaneously","одночасно","adverb","B2","general"],
["alternatively","альтернативно","adverb","B2","general"],
["conversely","навпаки","adverb","B2","general"],
["consequently","отже","adverb","B2","general"],
["subsequently","згодом","adverb","B2","general"],
["nonetheless","тим не менше","adverb","B2","general"],
["nevertheless","проте","adverb","B2","general"],
["notwithstanding","незважаючи на","adverb","B2","general"],
["accordingly","відповідно","adverb","B2","general"],
["predominantly","переважно","adverb","B2","general"],
["inherently","за своєю природою","adverb","B2","general"],
["explicitly","явно","adverb","B2","general"],
["implicitly","неявно","adverb","B2","general"],
["incidentally","між іншим","adverb","B2","general"],
["ironically","іронічно","adverb","B2","general"],
];

// Dedup & validate
const seen = new Set();
const validPos = new Set(["verb","noun","adjective","adverb","number","conjunction","preposition"]);
const validLevels = new Set(["A2","B1","B2"]);

const newWords4 = [];
let dupExist=0, dupInternal=0, bad=0;
for (const [en,ua,pos,level,topic] of RAW4) {
  const key = en.toLowerCase().trim();
  if (existSet.has(key))       { dupExist++; continue; }
  if (seen.has(key))           { dupInternal++; continue; }
  if (!validPos.has(pos) || !validLevels.has(level) || !en || !ua || !topic) { bad++; continue; }
  seen.add(key);
  newWords4.push({en,ua,pos,level,topic});
}
console.log(`Candidates: ${RAW4.length}, skip_exist: ${dupExist}, skip_dup: ${dupInternal}, bad: ${bad}`);
console.log(`New batch4: ${newWords4.length}`);
const byL={}, byP={};
newWords4.forEach(w=>{byL[w.level]=(byL[w.level]||0)+1; byP[w.pos]=(byP[w.pos]||0)+1;});
console.log('By level:', byL); console.log('By pos:', byP);
fs.writeFileSync('./new_batch4.json', JSON.stringify(newWords4, null, 2));
console.log('Wrote new_batch4.json');
